// ============================================================
//  NEXACORP EMPLOYEE DATASET  — Practice Data for JS Interviews
// ============================================================

const departments = [
  "Engineering",
  "Sales",
  "Marketing",
  "HR",
  "Finance",
  "Operations",
  "Design",
  "Legal",
];
const regions = ["North", "South", "East", "West", "Central"];
const skills = [
  "JavaScript",
  "React",
  "Node.js",
  "Python",
  "SQL",
  "AWS",
  "Docker",
  "TypeScript",
  "GraphQL",
  "Redis",
  "MongoDB",
  "Figma",
  "Excel",
  "Salesforce",
  "SAP",
];
const statuses = ["active", "inactive", "on_leave", "probation", "terminated"];
const roles = [
  "Intern",
  "Junior",
  "Mid",
  "Senior",
  "Lead",
  "Manager",
  "Director",
  "VP",
  "C-Suite",
];

const employees = [
  {
    id: "EMP001",
    name: "Aarav Mehta",
    age: 28,
    gender: "male",
    email: "aarav.mehta@nexacorp.com",
    phone: "+91-9876543210",
    department: "Engineering",
    role: "Senior",
    title: "Senior Software Engineer",
    region: "West",
    location: {
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
      remote: false,
    },
    status: "active",
    hireDate: "2019-03-15",
    salary: { base: 120000, bonus: 15000, currency: "INR", payGrade: "L4" },
    skills: ["JavaScript", "React", "Node.js", "TypeScript"],
    manager: "EMP010",
    teamSize: null,
    projects: [
      {
        id: "PRJ101",
        name: "Portal Redesign",
        status: "completed",
        hoursLogged: 340,
        budget: 500000,
      },
      {
        id: "PRJ102",
        name: "API Migration",
        status: "in_progress",
        hoursLogged: 120,
        budget: 300000,
      },
    ],
    performance: {
      rating: 4.5,
      year: 2024,
      promotionEligible: true,
      reviewDate: "2024-12-01",
    },
    leaves: { total: 24, used: 10, pending: 2 },
    certifications: [
      { name: "AWS Solutions Architect", issuer: "Amazon", year: 2022 },
    ],
    joinedAs: "Mid",
  },
  {
    id: "EMP002",
    name: "Priya Sharma",
    age: 32,
    gender: "female",
    email: "priya.sharma@nexacorp.com",
    phone: "+91-9812345678",
    department: "Sales",
    role: "Manager",
    title: "Sales Manager",
    region: "North",
    location: {
      city: "Delhi",
      state: "Delhi",
      country: "India",
      remote: false,
    },
    status: "active",
    hireDate: "2016-07-01",
    salary: { base: 150000, bonus: 40000, currency: "INR", payGrade: "L6" },
    skills: ["Salesforce", "Excel", "SQL"],
    manager: "EMP020",
    teamSize: 8,
    projects: [
      {
        id: "PRJ103",
        name: "Q4 Sales Drive",
        status: "in_progress",
        hoursLogged: 200,
        budget: 800000,
      },
      {
        id: "PRJ104",
        name: "CRM Upgrade",
        status: "completed",
        hoursLogged: 80,
        budget: 150000,
      },
    ],
    performance: {
      rating: 4.8,
      year: 2024,
      promotionEligible: true,
      reviewDate: "2024-11-15",
    },
    leaves: { total: 24, used: 18, pending: 0 },
    certifications: [
      { name: "Certified Sales Professional", issuer: "NASP", year: 2020 },
    ],
    joinedAs: "Junior",
  },
  {
    id: "EMP003",
    name: "Rohan Verma",
    age: 24,
    gender: "male",
    email: "rohan.verma@nexacorp.com",
    phone: "+91-9988776655",
    department: "Engineering",
    role: "Junior",
    title: "Junior Developer",
    region: "West",
    location: {
      city: "Pune",
      state: "Maharashtra",
      country: "India",
      remote: true,
    },
    status: "probation",
    hireDate: "2024-01-10",
    salary: { base: 60000, bonus: 0, currency: "INR", payGrade: "L2" },
    skills: ["JavaScript", "React", "Python"],
    manager: "EMP001",
    teamSize: null,
    projects: [
      {
        id: "PRJ102",
        name: "API Migration",
        status: "in_progress",
        hoursLogged: 60,
        budget: 300000,
      },
    ],
    performance: {
      rating: 3.2,
      year: 2024,
      promotionEligible: false,
      reviewDate: "2025-01-10",
    },
    leaves: { total: 12, used: 3, pending: 1 },
    certifications: [],
    joinedAs: "Intern",
  },
  {
    id: "EMP004",
    name: "Sneha Patel",
    age: 30,
    gender: "female",
    email: "sneha.patel@nexacorp.com",
    phone: "+91-9765432109",
    department: "Marketing",
    role: "Senior",
    title: "Senior Marketing Analyst",
    region: "West",
    location: {
      city: "Ahmedabad",
      state: "Gujarat",
      country: "India",
      remote: false,
    },
    status: "active",
    hireDate: "2018-05-20",
    salary: { base: 95000, bonus: 12000, currency: "INR", payGrade: "L4" },
    skills: ["Excel", "SQL", "Figma"],
    manager: "EMP015",
    teamSize: null,
    projects: [
      {
        id: "PRJ105",
        name: "Brand Refresh",
        status: "in_progress",
        hoursLogged: 150,
        budget: 600000,
      },
      {
        id: "PRJ106",
        name: "SEO Overhaul",
        status: "completed",
        hoursLogged: 90,
        budget: 200000,
      },
    ],
    performance: {
      rating: 4.1,
      year: 2024,
      promotionEligible: true,
      reviewDate: "2024-12-15",
    },
    leaves: { total: 24, used: 14, pending: 3 },
    certifications: [
      { name: "Google Analytics Certified", issuer: "Google", year: 2023 },
    ],
    joinedAs: "Mid",
  },
  {
    id: "EMP005",
    name: "Karan Singh",
    age: 38,
    gender: "male",
    email: "karan.singh@nexacorp.com",
    phone: "+91-9123456789",
    department: "Finance",
    role: "Director",
    title: "Finance Director",
    region: "North",
    location: {
      city: "Chandigarh",
      state: "Punjab",
      country: "India",
      remote: false,
    },
    status: "active",
    hireDate: "2012-02-28",
    salary: { base: 280000, bonus: 80000, currency: "INR", payGrade: "L8" },
    skills: ["SAP", "Excel", "SQL"],
    manager: "EMP025",
    teamSize: 15,
    projects: [
      {
        id: "PRJ107",
        name: "Budget Restructure",
        status: "completed",
        hoursLogged: 500,
        budget: 1200000,
      },
      {
        id: "PRJ108",
        name: "Tax Compliance 2024",
        status: "in_progress",
        hoursLogged: 200,
        budget: 400000,
      },
    ],
    performance: {
      rating: 4.7,
      year: 2024,
      promotionEligible: false,
      reviewDate: "2024-10-01",
    },
    leaves: { total: 30, used: 22, pending: 0 },
    certifications: [
      { name: "CFA Level 3", issuer: "CFA Institute", year: 2015 },
      { name: "CPA", issuer: "AICPA", year: 2013 },
    ],
    joinedAs: "Senior",
  },
  {
    id: "EMP006",
    name: "Divya Nair",
    age: 27,
    gender: "female",
    email: "divya.nair@nexacorp.com",
    phone: "+91-9234567890",
    department: "Design",
    role: "Mid",
    title: "UI/UX Designer",
    region: "South",
    location: {
      city: "Bangalore",
      state: "Karnataka",
      country: "India",
      remote: true,
    },
    status: "active",
    hireDate: "2021-06-14",
    salary: { base: 85000, bonus: 8000, currency: "INR", payGrade: "L3" },
    skills: ["Figma", "JavaScript", "React"],
    manager: "EMP016",
    teamSize: null,
    projects: [
      {
        id: "PRJ101",
        name: "Portal Redesign",
        status: "completed",
        hoursLogged: 280,
        budget: 500000,
      },
      {
        id: "PRJ105",
        name: "Brand Refresh",
        status: "in_progress",
        hoursLogged: 100,
        budget: 600000,
      },
    ],
    performance: {
      rating: 4.3,
      year: 2024,
      promotionEligible: true,
      reviewDate: "2024-12-20",
    },
    leaves: { total: 24, used: 8, pending: 4 },
    certifications: [
      { name: "Google UX Design", issuer: "Google", year: 2022 },
    ],
    joinedAs: "Junior",
  },
  {
    id: "EMP007",
    name: "Amit Joshi",
    age: 35,
    gender: "male",
    email: "amit.joshi@nexacorp.com",
    phone: "+91-9345678901",
    department: "Operations",
    role: "Lead",
    title: "Operations Lead",
    region: "Central",
    location: {
      city: "Bhopal",
      state: "Madhya Pradesh",
      country: "India",
      remote: false,
    },
    status: "on_leave",
    hireDate: "2014-09-03",
    salary: { base: 130000, bonus: 20000, currency: "INR", payGrade: "L5" },
    skills: ["SAP", "Excel", "SQL", "Python"],
    manager: "EMP022",
    teamSize: 6,
    projects: [
      {
        id: "PRJ109",
        name: "Warehouse Automation",
        status: "in_progress",
        hoursLogged: 400,
        budget: 2000000,
      },
    ],
    performance: {
      rating: 4.0,
      year: 2024,
      promotionEligible: false,
      reviewDate: "2024-09-03",
    },
    leaves: { total: 24, used: 24, pending: 5 },
    certifications: [
      { name: "Six Sigma Green Belt", issuer: "ASQ", year: 2018 },
    ],
    joinedAs: "Mid",
  },
  {
    id: "EMP008",
    name: "Meera Iyer",
    age: 29,
    gender: "female",
    email: "meera.iyer@nexacorp.com",
    phone: "+91-9456789012",
    department: "HR",
    role: "Senior",
    title: "Senior HR Business Partner",
    region: "South",
    location: {
      city: "Chennai",
      state: "Tamil Nadu",
      country: "India",
      remote: false,
    },
    status: "active",
    hireDate: "2019-11-11",
    salary: { base: 100000, bonus: 10000, currency: "INR", payGrade: "L4" },
    skills: ["Excel", "SQL"],
    manager: "EMP018",
    teamSize: null,
    projects: [
      {
        id: "PRJ110",
        name: "Talent Acquisition Drive",
        status: "completed",
        hoursLogged: 200,
        budget: 300000,
      },
      {
        id: "PRJ111",
        name: "Employee Wellness Program",
        status: "in_progress",
        hoursLogged: 60,
        budget: 150000,
      },
    ],
    performance: {
      rating: 4.2,
      year: 2024,
      promotionEligible: true,
      reviewDate: "2024-11-11",
    },
    leaves: { total: 24, used: 12, pending: 0 },
    certifications: [{ name: "SHRM-CP", issuer: "SHRM", year: 2021 }],
    joinedAs: "Mid",
  },
  {
    id: "EMP009",
    name: "Vikram Reddy",
    age: 33,
    gender: "male",
    email: "vikram.reddy@nexacorp.com",
    phone: "+91-9567890123",
    department: "Engineering",
    role: "Lead",
    title: "Tech Lead",
    region: "South",
    location: {
      city: "Hyderabad",
      state: "Telangana",
      country: "India",
      remote: false,
    },
    status: "active",
    hireDate: "2015-04-22",
    salary: { base: 160000, bonus: 25000, currency: "INR", payGrade: "L5" },
    skills: ["JavaScript", "TypeScript", "Node.js", "AWS", "Docker", "MongoDB"],
    manager: "EMP010",
    teamSize: 5,
    projects: [
      {
        id: "PRJ112",
        name: "Microservices Refactor",
        status: "in_progress",
        hoursLogged: 500,
        budget: 1500000,
      },
      {
        id: "PRJ102",
        name: "API Migration",
        status: "in_progress",
        hoursLogged: 200,
        budget: 300000,
      },
    ],
    performance: {
      rating: 4.6,
      year: 2024,
      promotionEligible: true,
      reviewDate: "2024-04-22",
    },
    leaves: { total: 24, used: 6, pending: 0 },
    certifications: [
      {
        name: "AWS Solutions Architect Professional",
        issuer: "Amazon",
        year: 2021,
      },
      { name: "Kubernetes Administrator", issuer: "CNCF", year: 2023 },
    ],
    joinedAs: "Junior",
  },
  {
    id: "EMP010",
    name: "Nisha Kapoor",
    age: 41,
    gender: "female",
    email: "nisha.kapoor@nexacorp.com",
    phone: "+91-9678901234",
    department: "Engineering",
    role: "VP",
    title: "VP of Engineering",
    region: "West",
    location: {
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
      remote: false,
    },
    status: "active",
    hireDate: "2010-01-05",
    salary: { base: 450000, bonus: 150000, currency: "INR", payGrade: "L9" },
    skills: ["JavaScript", "Python", "AWS", "Docker", "GraphQL"],
    manager: "EMP030",
    teamSize: 40,
    projects: [
      {
        id: "PRJ101",
        name: "Portal Redesign",
        status: "completed",
        hoursLogged: 100,
        budget: 500000,
      },
      {
        id: "PRJ112",
        name: "Microservices Refactor",
        status: "in_progress",
        hoursLogged: 150,
        budget: 1500000,
      },
    ],
    performance: {
      rating: 4.9,
      year: 2024,
      promotionEligible: false,
      reviewDate: "2024-01-05",
    },
    leaves: { total: 30, used: 15, pending: 0 },
    certifications: [
      {
        name: "AWS Solutions Architect Professional",
        issuer: "Amazon",
        year: 2019,
      },
      { name: "PMP", issuer: "PMI", year: 2016 },
    ],
    joinedAs: "Senior",
  },
  {
    id: "EMP011",
    name: "Saurabh Gupta",
    age: 26,
    gender: "male",
    email: "saurabh.gupta@nexacorp.com",
    phone: "+91-9789012345",
    department: "Engineering",
    role: "Junior",
    title: "Junior Backend Developer",
    region: "North",
    location: { city: "Noida", state: "UP", country: "India", remote: true },
    status: "active",
    hireDate: "2023-07-01",
    salary: { base: 65000, bonus: 5000, currency: "INR", payGrade: "L2" },
    skills: ["Python", "SQL", "Docker", "Redis"],
    manager: "EMP009",
    teamSize: null,
    projects: [
      {
        id: "PRJ112",
        name: "Microservices Refactor",
        status: "in_progress",
        hoursLogged: 80,
        budget: 1500000,
      },
    ],
    performance: {
      rating: 3.8,
      year: 2024,
      promotionEligible: false,
      reviewDate: "2025-07-01",
    },
    leaves: { total: 18, used: 5, pending: 0 },
    certifications: [],
    joinedAs: "Intern",
  },
  {
    id: "EMP012",
    name: "Tanvi Bhatt",
    age: 31,
    gender: "female",
    email: "tanvi.bhatt@nexacorp.com",
    phone: "+91-9890123456",
    department: "Sales",
    role: "Senior",
    title: "Senior Sales Executive",
    region: "West",
    location: {
      city: "Surat",
      state: "Gujarat",
      country: "India",
      remote: false,
    },
    status: "active",
    hireDate: "2017-03-08",
    salary: { base: 110000, bonus: 35000, currency: "INR", payGrade: "L4" },
    skills: ["Salesforce", "Excel"],
    manager: "EMP002",
    teamSize: null,
    projects: [
      {
        id: "PRJ103",
        name: "Q4 Sales Drive",
        status: "in_progress",
        hoursLogged: 180,
        budget: 800000,
      },
    ],
    performance: {
      rating: 4.4,
      year: 2024,
      promotionEligible: true,
      reviewDate: "2024-03-08",
    },
    leaves: { total: 24, used: 20, pending: 2 },
    certifications: [
      { name: "Salesforce Admin", issuer: "Salesforce", year: 2021 },
    ],
    joinedAs: "Junior",
  },
  {
    id: "EMP013",
    name: "Harsh Malhotra",
    age: 22,
    gender: "male",
    email: "harsh.malhotra@nexacorp.com",
    phone: "+91-9901234567",
    department: "Engineering",
    role: "Intern",
    title: "Software Engineering Intern",
    region: "North",
    location: { city: "Delhi", state: "Delhi", country: "India", remote: true },
    status: "active",
    hireDate: "2024-06-01",
    salary: { base: 25000, bonus: 0, currency: "INR", payGrade: "L1" },
    skills: ["JavaScript", "React"],
    manager: "EMP003",
    teamSize: null,
    projects: [
      {
        id: "PRJ101",
        name: "Portal Redesign",
        status: "completed",
        hoursLogged: 30,
        budget: 500000,
      },
    ],
    performance: {
      rating: 3.5,
      year: 2024,
      promotionEligible: false,
      reviewDate: "2024-12-01",
    },
    leaves: { total: 6, used: 1, pending: 0 },
    certifications: [],
    joinedAs: "Intern",
  },
  {
    id: "EMP014",
    name: "Pooja Desai",
    age: 36,
    gender: "female",
    email: "pooja.desai@nexacorp.com",
    phone: "+91-9012345678",
    department: "Legal",
    role: "Senior",
    title: "Senior Legal Counsel",
    region: "West",
    location: {
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
      remote: false,
    },
    status: "active",
    hireDate: "2013-08-19",
    salary: { base: 200000, bonus: 30000, currency: "INR", payGrade: "L6" },
    skills: ["Excel", "SQL"],
    manager: "EMP026",
    teamSize: null,
    projects: [
      {
        id: "PRJ113",
        name: "Contract Modernization",
        status: "in_progress",
        hoursLogged: 300,
        budget: 700000,
      },
    ],
    performance: {
      rating: 4.6,
      year: 2024,
      promotionEligible: true,
      reviewDate: "2024-08-19",
    },
    leaves: { total: 24, used: 9, pending: 1 },
    certifications: [
      { name: "Bar Council of India", issuer: "BCI", year: 2011 },
    ],
    joinedAs: "Mid",
  },
  {
    id: "EMP015",
    name: "Rahul Tiwari",
    age: 40,
    gender: "male",
    email: "rahul.tiwari@nexacorp.com",
    phone: "+91-9112345670",
    department: "Marketing",
    role: "Director",
    title: "Marketing Director",
    region: "North",
    location: { city: "Lucknow", state: "UP", country: "India", remote: false },
    status: "active",
    hireDate: "2011-10-30",
    salary: { base: 320000, bonus: 90000, currency: "INR", payGrade: "L8" },
    skills: ["SQL", "Excel", "Figma"],
    manager: "EMP025",
    teamSize: 12,
    projects: [
      {
        id: "PRJ105",
        name: "Brand Refresh",
        status: "in_progress",
        hoursLogged: 120,
        budget: 600000,
      },
      {
        id: "PRJ114",
        name: "Digital Transformation",
        status: "planning",
        hoursLogged: 0,
        budget: 3000000,
      },
    ],
    performance: {
      rating: 4.5,
      year: 2024,
      promotionEligible: false,
      reviewDate: "2024-10-30",
    },
    leaves: { total: 30, used: 25, pending: 0 },
    certifications: [
      { name: "Digital Marketing Pro", issuer: "HubSpot", year: 2020 },
    ],
    joinedAs: "Mid",
  },
  {
    id: "EMP016",
    name: "Anjali Menon",
    age: 34,
    gender: "female",
    email: "anjali.menon@nexacorp.com",
    phone: "+91-9223456781",
    department: "Design",
    role: "Lead",
    title: "Design Lead",
    region: "South",
    location: {
      city: "Kochi",
      state: "Kerala",
      country: "India",
      remote: true,
    },
    status: "active",
    hireDate: "2016-02-14",
    salary: { base: 145000, bonus: 18000, currency: "INR", payGrade: "L5" },
    skills: ["Figma", "JavaScript", "React", "GraphQL"],
    manager: "EMP010",
    teamSize: 4,
    projects: [
      {
        id: "PRJ101",
        name: "Portal Redesign",
        status: "completed",
        hoursLogged: 400,
        budget: 500000,
      },
      {
        id: "PRJ105",
        name: "Brand Refresh",
        status: "in_progress",
        hoursLogged: 200,
        budget: 600000,
      },
    ],
    performance: {
      rating: 4.7,
      year: 2024,
      promotionEligible: true,
      reviewDate: "2024-02-14",
    },
    leaves: { total: 24, used: 11, pending: 0 },
    certifications: [
      { name: "Interaction Design Foundation", issuer: "IDF", year: 2019 },
    ],
    joinedAs: "Mid",
  },
  {
    id: "EMP017",
    name: "Nikhil Rao",
    age: 29,
    gender: "male",
    email: "nikhil.rao@nexacorp.com",
    phone: "+91-9334567892",
    department: "Engineering",
    role: "Mid",
    title: "Full Stack Developer",
    region: "South",
    location: {
      city: "Bangalore",
      state: "Karnataka",
      country: "India",
      remote: false,
    },
    status: "active",
    hireDate: "2020-09-01",
    salary: { base: 95000, bonus: 10000, currency: "INR", payGrade: "L3" },
    skills: ["JavaScript", "React", "Node.js", "MongoDB", "Docker"],
    manager: "EMP009",
    teamSize: null,
    projects: [
      {
        id: "PRJ112",
        name: "Microservices Refactor",
        status: "in_progress",
        hoursLogged: 250,
        budget: 1500000,
      },
      {
        id: "PRJ101",
        name: "Portal Redesign",
        status: "completed",
        hoursLogged: 180,
        budget: 500000,
      },
    ],
    performance: {
      rating: 4.0,
      year: 2024,
      promotionEligible: true,
      reviewDate: "2024-09-01",
    },
    leaves: { total: 24, used: 13, pending: 2 },
    certifications: [
      { name: "MongoDB Developer", issuer: "MongoDB Inc.", year: 2022 },
    ],
    joinedAs: "Junior",
  },
  {
    id: "EMP018",
    name: "Sunita Pillai",
    age: 43,
    gender: "female",
    email: "sunita.pillai@nexacorp.com",
    phone: "+91-9445678903",
    department: "HR",
    role: "Director",
    title: "HR Director",
    region: "South",
    location: {
      city: "Chennai",
      state: "Tamil Nadu",
      country: "India",
      remote: false,
    },
    status: "active",
    hireDate: "2009-05-05",
    salary: { base: 300000, bonus: 75000, currency: "INR", payGrade: "L8" },
    skills: ["Excel", "SQL"],
    manager: "EMP025",
    teamSize: 10,
    projects: [
      {
        id: "PRJ110",
        name: "Talent Acquisition Drive",
        status: "completed",
        hoursLogged: 150,
        budget: 300000,
      },
      {
        id: "PRJ115",
        name: "HRIS Implementation",
        status: "in_progress",
        hoursLogged: 300,
        budget: 1000000,
      },
    ],
    performance: {
      rating: 4.8,
      year: 2024,
      promotionEligible: false,
      reviewDate: "2024-05-05",
    },
    leaves: { total: 30, used: 20, pending: 0 },
    certifications: [
      { name: "SHRM-SCP", issuer: "SHRM", year: 2017 },
      { name: "SPHR", issuer: "HRCI", year: 2014 },
    ],
    joinedAs: "Mid",
  },
  {
    id: "EMP019",
    name: "Gaurav Saxena",
    age: 25,
    gender: "male",
    email: "gaurav.saxena@nexacorp.com",
    phone: "+91-9556789014",
    department: "Marketing",
    role: "Junior",
    title: "Marketing Executive",
    region: "Central",
    location: {
      city: "Indore",
      state: "Madhya Pradesh",
      country: "India",
      remote: true,
    },
    status: "active",
    hireDate: "2023-01-16",
    salary: { base: 55000, bonus: 4000, currency: "INR", payGrade: "L2" },
    skills: ["Excel", "Figma", "SQL"],
    manager: "EMP015",
    teamSize: null,
    projects: [
      {
        id: "PRJ106",
        name: "SEO Overhaul",
        status: "completed",
        hoursLogged: 120,
        budget: 200000,
      },
    ],
    performance: {
      rating: 3.7,
      year: 2024,
      promotionEligible: false,
      reviewDate: "2025-01-16",
    },
    leaves: { total: 18, used: 7, pending: 1 },
    certifications: [],
    joinedAs: "Intern",
  },
  {
    id: "EMP020",
    name: "Anita Choudhary",
    age: 46,
    gender: "female",
    email: "anita.choudhary@nexacorp.com",
    phone: "+91-9667890125",
    department: "Sales",
    role: "VP",
    title: "VP of Sales",
    region: "North",
    location: {
      city: "Delhi",
      state: "Delhi",
      country: "India",
      remote: false,
    },
    status: "active",
    hireDate: "2008-11-01",
    salary: { base: 500000, bonus: 200000, currency: "INR", payGrade: "L9" },
    skills: ["Salesforce", "Excel", "SQL"],
    manager: "EMP030",
    teamSize: 50,
    projects: [
      {
        id: "PRJ103",
        name: "Q4 Sales Drive",
        status: "in_progress",
        hoursLogged: 80,
        budget: 800000,
      },
      {
        id: "PRJ116",
        name: "Market Expansion East",
        status: "planning",
        hoursLogged: 0,
        budget: 5000000,
      },
    ],
    performance: {
      rating: 4.9,
      year: 2024,
      promotionEligible: false,
      reviewDate: "2024-11-01",
    },
    leaves: { total: 30, used: 28, pending: 0 },
    certifications: [
      { name: "Strategic Sales Management", issuer: "Kellogg", year: 2010 },
    ],
    joinedAs: "Senior",
  },
  {
    id: "EMP021",
    name: "Ravi Kumar",
    age: 37,
    gender: "male",
    email: "ravi.kumar@nexacorp.com",
    phone: "+91-9778901236",
    department: "Engineering",
    role: "Senior",
    title: "Senior DevOps Engineer",
    region: "East",
    location: {
      city: "Kolkata",
      state: "West Bengal",
      country: "India",
      remote: false,
    },
    status: "inactive",
    hireDate: "2017-06-10",
    salary: { base: 125000, bonus: 0, currency: "INR", payGrade: "L4" },
    skills: ["AWS", "Docker", "Python", "Redis", "MongoDB"],
    manager: "EMP009",
    teamSize: null,
    projects: [],
    performance: {
      rating: 2.5,
      year: 2024,
      promotionEligible: false,
      reviewDate: "2024-06-10",
    },
    leaves: { total: 24, used: 24, pending: 8 },
    certifications: [
      { name: "AWS DevOps Professional", issuer: "Amazon", year: 2020 },
    ],
    joinedAs: "Mid",
  },
  {
    id: "EMP022",
    name: "Leela Krishnamurthy",
    age: 44,
    gender: "female",
    email: "leela.k@nexacorp.com",
    phone: "+91-9889012347",
    department: "Operations",
    role: "Director",
    title: "Operations Director",
    region: "Central",
    location: {
      city: "Nagpur",
      state: "Maharashtra",
      country: "India",
      remote: false,
    },
    status: "active",
    hireDate: "2010-07-22",
    salary: { base: 290000, bonus: 70000, currency: "INR", payGrade: "L8" },
    skills: ["SAP", "Excel", "SQL", "Python"],
    manager: "EMP025",
    teamSize: 20,
    projects: [
      {
        id: "PRJ109",
        name: "Warehouse Automation",
        status: "in_progress",
        hoursLogged: 350,
        budget: 2000000,
      },
      {
        id: "PRJ117",
        name: "Supply Chain Optimization",
        status: "planning",
        hoursLogged: 0,
        budget: 4000000,
      },
    ],
    performance: {
      rating: 4.6,
      year: 2024,
      promotionEligible: true,
      reviewDate: "2024-07-22",
    },
    leaves: { total: 30, used: 18, pending: 0 },
    certifications: [
      { name: "PMP", issuer: "PMI", year: 2014 },
      { name: "Six Sigma Black Belt", issuer: "ASQ", year: 2016 },
    ],
    joinedAs: "Senior",
  },
  {
    id: "EMP023",
    name: "Dev Arora",
    age: 28,
    gender: "male",
    email: "dev.arora@nexacorp.com",
    phone: "+91-9990123458",
    department: "Engineering",
    role: "Mid",
    title: "Mobile Developer",
    region: "North",
    location: {
      city: "Gurgaon",
      state: "Haryana",
      country: "India",
      remote: true,
    },
    status: "active",
    hireDate: "2021-03-15",
    salary: { base: 90000, bonus: 9000, currency: "INR", payGrade: "L3" },
    skills: ["JavaScript", "React", "TypeScript", "GraphQL"],
    manager: "EMP001",
    teamSize: null,
    projects: [
      {
        id: "PRJ118",
        name: "Mobile App v2",
        status: "in_progress",
        hoursLogged: 300,
        budget: 1200000,
      },
    ],
    performance: {
      rating: 4.1,
      year: 2024,
      promotionEligible: false,
      reviewDate: "2024-03-15",
    },
    leaves: { total: 24, used: 9, pending: 3 },
    certifications: [],
    joinedAs: "Junior",
  },
  {
    id: "EMP024",
    name: "Kavya Bhat",
    age: 30,
    gender: "female",
    email: "kavya.bhat@nexacorp.com",
    phone: "+91-9101234569",
    department: "Finance",
    role: "Mid",
    title: "Financial Analyst",
    region: "South",
    location: {
      city: "Mangalore",
      state: "Karnataka",
      country: "India",
      remote: false,
    },
    status: "active",
    hireDate: "2020-01-20",
    salary: { base: 88000, bonus: 7000, currency: "INR", payGrade: "L3" },
    skills: ["SAP", "Excel", "SQL"],
    manager: "EMP005",
    teamSize: null,
    projects: [
      {
        id: "PRJ107",
        name: "Budget Restructure",
        status: "completed",
        hoursLogged: 180,
        budget: 1200000,
      },
      {
        id: "PRJ108",
        name: "Tax Compliance 2024",
        status: "in_progress",
        hoursLogged: 120,
        budget: 400000,
      },
    ],
    performance: {
      rating: 4.0,
      year: 2024,
      promotionEligible: true,
      reviewDate: "2025-01-20",
    },
    leaves: { total: 24, used: 10, pending: 0 },
    certifications: [
      { name: "CFA Level 1", issuer: "CFA Institute", year: 2022 },
    ],
    joinedAs: "Junior",
  },
  {
    id: "EMP025",
    name: "Suresh Nambiar",
    age: 52,
    gender: "male",
    email: "suresh.nambiar@nexacorp.com",
    phone: "+91-9212345670",
    department: "Operations",
    role: "C-Suite",
    title: "Chief Operating Officer",
    region: "South",
    location: {
      city: "Bangalore",
      state: "Karnataka",
      country: "India",
      remote: false,
    },
    status: "active",
    hireDate: "2006-04-01",
    salary: { base: 800000, bonus: 400000, currency: "INR", payGrade: "C1" },
    skills: ["SAP", "Excel", "SQL", "Python"],
    manager: "EMP030",
    teamSize: 200,
    projects: [
      {
        id: "PRJ114",
        name: "Digital Transformation",
        status: "planning",
        hoursLogged: 50,
        budget: 3000000,
      },
      {
        id: "PRJ117",
        name: "Supply Chain Optimization",
        status: "planning",
        hoursLogged: 30,
        budget: 4000000,
      },
    ],
    performance: {
      rating: 4.9,
      year: 2024,
      promotionEligible: false,
      reviewDate: "2024-04-01",
    },
    leaves: { total: 30, used: 10, pending: 0 },
    certifications: [
      { name: "PMP", issuer: "PMI", year: 2008 },
      { name: "Six Sigma Black Belt", issuer: "ASQ", year: 2005 },
    ],
    joinedAs: "Director",
  },
];
