// ============================================================
//  INTERVIEW PRACTICE DATASET
//  Use this for all 15 JS questions
//  50 customers · ~200 orders · 4 regions · 3 tiers
// ============================================================

const customers = [
  {
    customerId: "C001",
    name: "Ankit Mehta",
    email: "ankit.mehta@example.com",
    region: "North",
    tier: "premium",
    joinedAt: "2022-03-15",
    address: { city: "Delhi", state: "Delhi", pincode: "110001" },
    orders: [
      {
        orderId: "ORD-1001",
        placedAt: "2025-01-10T10:30:00Z",
        status: "delivered",
        couponApplied: "SAVE10",
        discountPercent: 10,
        items: [
          {
            productId: "P-19",
            productName: "Wireless Earbuds",
            category: "Electronics",
            quantity: 2,
            unitPrice: 1499,
            itemStatus: "delivered",
          },
          {
            productId: "P-07",
            productName: "USB-C Hub",
            category: "Electronics",
            quantity: 1,
            unitPrice: 899,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "UPI",
          status: "paid",
          paidAt: "2025-01-10T10:31:00Z",
        },
        delivery: {
          estimatedDate: "2025-01-14",
          actualDate: "2025-01-13",
          deliveredOnTime: true,
        },
      },
      {
        orderId: "ORD-1002",
        placedAt: "2025-02-18T14:00:00Z",
        status: "delivered",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-03",
            productName: "Mechanical Keyboard",
            category: "Electronics",
            quantity: 1,
            unitPrice: 3499,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "Card",
          status: "paid",
          paidAt: "2025-02-18T14:02:00Z",
        },
        delivery: {
          estimatedDate: "2025-02-22",
          actualDate: "2025-02-25",
          deliveredOnTime: false,
        },
      },
      {
        orderId: "ORD-1003",
        placedAt: "2025-03-22T09:00:00Z",
        status: "pending",
        couponApplied: "FLAT200",
        discountPercent: 5,
        items: [
          {
            productId: "P-12",
            productName: "Desk Lamp",
            category: "Home",
            quantity: 1,
            unitPrice: 1299,
            itemStatus: "pending",
          },
        ],
        payment: { method: "UPI", status: "pending", paidAt: null },
        delivery: {
          estimatedDate: "2025-03-26",
          actualDate: null,
          deliveredOnTime: null,
        },
      },
    ],
    reviews: [
      { productId: "P-19", rating: 5, helpful: 18, verified: true },
      { productId: "P-03", rating: 4, helpful: 7, verified: true },
    ],
  },

  {
    customerId: "C002",
    name: "Priya Shah",
    email: "priya.shah@example.com",
    region: "West",
    tier: "enterprise",
    joinedAt: "2021-08-20",
    address: { city: "Mumbai", state: "Maharashtra", pincode: "400001" },
    orders: [
      {
        orderId: "ORD-1004",
        placedAt: "2024-11-05T11:00:00Z",
        status: "delivered",
        couponApplied: "SAVE10",
        discountPercent: 10,
        items: [
          {
            productId: "P-02",
            productName: "Standing Desk",
            category: "Furniture",
            quantity: 1,
            unitPrice: 12999,
            itemStatus: "delivered",
          },
          {
            productId: "P-11",
            productName: "Monitor Arm",
            category: "Furniture",
            quantity: 2,
            unitPrice: 2499,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "Card",
          status: "paid",
          paidAt: "2024-11-05T11:05:00Z",
        },
        delivery: {
          estimatedDate: "2024-11-10",
          actualDate: "2024-11-09",
          deliveredOnTime: true,
        },
      },
      {
        orderId: "ORD-1005",
        placedAt: "2025-01-28T16:00:00Z",
        status: "shipped",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-19",
            productName: "Wireless Earbuds",
            category: "Electronics",
            quantity: 3,
            unitPrice: 1499,
            itemStatus: "shipped",
          },
        ],
        payment: {
          method: "Wallet",
          status: "paid",
          paidAt: "2025-01-28T16:01:00Z",
        },
        delivery: {
          estimatedDate: "2025-02-01",
          actualDate: null,
          deliveredOnTime: null,
        },
      },
    ],
    reviews: [{ productId: "P-02", rating: 5, helpful: 34, verified: true }],
  },

  {
    customerId: "C003",
    name: "Meera Joshi",
    email: "meera.joshi@example.com",
    region: "South",
    tier: "basic",
    joinedAt: "2023-01-10",
    address: { city: "Bangalore", state: "Karnataka", pincode: "560001" },
    orders: [
      {
        orderId: "ORD-1006",
        placedAt: "2025-01-15T08:00:00Z",
        status: "delivered",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-08",
            productName: "Clean Code (Book)",
            category: "Books",
            quantity: 1,
            unitPrice: 599,
            itemStatus: "delivered",
          },
          {
            productId: "P-09",
            productName: "You Don't Know JS",
            category: "Books",
            quantity: 1,
            unitPrice: 499,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "COD",
          status: "paid",
          paidAt: "2025-01-18T10:00:00Z",
        },
        delivery: {
          estimatedDate: "2025-01-18",
          actualDate: "2025-01-18",
          deliveredOnTime: true,
        },
      },
      {
        orderId: "ORD-1007",
        placedAt: "2025-02-01T12:00:00Z",
        status: "cancelled",
        couponApplied: "SAVE10",
        discountPercent: 10,
        items: [
          {
            productId: "P-03",
            productName: "Mechanical Keyboard",
            category: "Electronics",
            quantity: 1,
            unitPrice: 3499,
            itemStatus: "cancelled",
          },
        ],
        payment: {
          method: "UPI",
          status: "refunded",
          paidAt: "2025-02-01T12:01:00Z",
        },
        delivery: {
          estimatedDate: null,
          actualDate: null,
          deliveredOnTime: null,
        },
      },
      {
        orderId: "ORD-1044",
        placedAt: "2025-02-08T09:30:00Z",
        status: "pending",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-15",
            productName: "Yoga Mat",
            category: "Sports",
            quantity: 1,
            unitPrice: 899,
            itemStatus: "pending",
          },
          {
            productId: "P-16",
            productName: "Water Bottle",
            category: "Sports",
            quantity: 2,
            unitPrice: 349,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "UPI",
          status: "paid",
          paidAt: "2025-02-08T09:31:00Z",
        },
        delivery: {
          estimatedDate: "2025-02-12",
          actualDate: null,
          deliveredOnTime: null,
        },
      },
    ],
    reviews: [
      { productId: "P-08", rating: 5, helpful: 21, verified: true },
      { productId: "P-09", rating: 4, helpful: 9, verified: true },
    ],
  },

  {
    customerId: "C004",
    name: "Raj Patel",
    email: "raj.patel@example.com",
    region: "West",
    tier: "premium",
    joinedAt: "2022-11-01",
    address: { city: "Ahmedabad", state: "Gujarat", pincode: "380001" },
    orders: [
      {
        orderId: "ORD-1008",
        placedAt: "2024-12-20T15:00:00Z",
        status: "delivered",
        couponApplied: "FLAT200",
        discountPercent: 8,
        items: [
          {
            productId: "P-19",
            productName: "Wireless Earbuds",
            category: "Electronics",
            quantity: 1,
            unitPrice: 1499,
            itemStatus: "delivered",
          },
          {
            productId: "P-20",
            productName: "Smart Watch",
            category: "Electronics",
            quantity: 1,
            unitPrice: 4999,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "Card",
          status: "paid",
          paidAt: "2024-12-20T15:02:00Z",
        },
        delivery: {
          estimatedDate: "2024-12-24",
          actualDate: "2024-12-26",
          deliveredOnTime: false,
        },
      },
      {
        orderId: "ORD-1009",
        placedAt: "2025-03-01T10:00:00Z",
        status: "delivered",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-03",
            productName: "Mechanical Keyboard",
            category: "Electronics",
            quantity: 2,
            unitPrice: 3499,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "UPI",
          status: "paid",
          paidAt: "2025-03-01T10:01:00Z",
        },
        delivery: {
          estimatedDate: "2025-03-05",
          actualDate: "2025-03-04",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [
      { productId: "P-20", rating: 4, helpful: 11, verified: true },
      { productId: "P-19", rating: 3, helpful: 2, verified: false },
    ],
  },

  {
    customerId: "C005",
    name: "Sunita Rao",
    email: "sunita.rao@example.com",
    region: "South",
    tier: "premium",
    joinedAt: "2021-05-14",
    address: { city: "Chennai", state: "Tamil Nadu", pincode: "600001" },
    orders: [
      {
        orderId: "ORD-1010",
        placedAt: "2025-01-05T09:00:00Z",
        status: "delivered",
        couponApplied: "SAVE10",
        discountPercent: 10,
        items: [
          {
            productId: "P-02",
            productName: "Standing Desk",
            category: "Furniture",
            quantity: 1,
            unitPrice: 12999,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "Card",
          status: "paid",
          paidAt: "2025-01-05T09:02:00Z",
        },
        delivery: {
          estimatedDate: "2025-01-10",
          actualDate: "2025-01-09",
          deliveredOnTime: true,
        },
      },
      {
        orderId: "ORD-1011",
        placedAt: "2025-02-14T17:00:00Z",
        status: "processing",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-13",
            productName: "Air Purifier",
            category: "Home",
            quantity: 1,
            unitPrice: 7999,
            itemStatus: "processing",
          },
        ],
        payment: {
          method: "UPI",
          status: "paid",
          paidAt: "2025-02-14T17:01:00Z",
        },
        delivery: {
          estimatedDate: "2025-02-18",
          actualDate: null,
          deliveredOnTime: null,
        },
      },
    ],
    reviews: [{ productId: "P-02", rating: 5, helpful: 42, verified: true }],
  },

  {
    customerId: "C006",
    name: "Vikram Nair",
    email: "vikram.nair@example.com",
    region: "South",
    tier: "basic",
    joinedAt: "2023-06-22",
    address: { city: "Hyderabad", state: "Telangana", pincode: "500001" },
    orders: [
      {
        orderId: "ORD-1012",
        placedAt: "2024-11-20T13:00:00Z",
        status: "delivered",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-08",
            productName: "Clean Code (Book)",
            category: "Books",
            quantity: 2,
            unitPrice: 599,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "COD",
          status: "paid",
          paidAt: "2024-11-23T10:00:00Z",
        },
        delivery: {
          estimatedDate: "2024-11-24",
          actualDate: "2024-11-26",
          deliveredOnTime: false,
        },
      },
    ],
    reviews: [{ productId: "P-08", rating: 4, helpful: 6, verified: true }],
  },

  {
    customerId: "C007",
    name: "Deepa Krishnan",
    email: "deepa.k@example.com",
    region: "East",
    tier: "enterprise",
    joinedAt: "2020-12-01",
    address: { city: "Kolkata", state: "West Bengal", pincode: "700001" },
    orders: [
      {
        orderId: "ORD-1013",
        placedAt: "2025-02-20T11:00:00Z",
        status: "delivered",
        couponApplied: "FLAT200",
        discountPercent: 12,
        items: [
          {
            productId: "P-21",
            productName: "Ergonomic Chair",
            category: "Furniture",
            quantity: 2,
            unitPrice: 8999,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "Card",
          status: "paid",
          paidAt: "2025-02-20T11:03:00Z",
        },
        delivery: {
          estimatedDate: "2025-02-25",
          actualDate: "2025-02-27",
          deliveredOnTime: false,
        },
      },
      {
        orderId: "ORD-1033",
        placedAt: "2025-01-22T08:00:00Z",
        status: "pending",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-22",
            productName: "Laptop Stand",
            category: "Electronics",
            quantity: 1,
            unitPrice: 1999,
            itemStatus: "pending",
          },
        ],
        payment: { method: "UPI", status: "failed", paidAt: null },
        delivery: {
          estimatedDate: "2025-01-26",
          actualDate: null,
          deliveredOnTime: null,
        },
      },
    ],
    reviews: [{ productId: "P-21", rating: 5, helpful: 29, verified: true }],
  },

  {
    customerId: "C008",
    name: "Arjun Singh",
    email: "arjun.singh@example.com",
    region: "North",
    tier: "premium",
    joinedAt: "2022-07-18",
    address: { city: "Jaipur", state: "Rajasthan", pincode: "302001" },
    orders: [
      {
        orderId: "ORD-1014",
        placedAt: "2025-01-08T14:00:00Z",
        status: "delivered",
        couponApplied: "SAVE10",
        discountPercent: 10,
        items: [
          {
            productId: "P-19",
            productName: "Wireless Earbuds",
            category: "Electronics",
            quantity: 4,
            unitPrice: 1499,
            itemStatus: "delivered",
          },
          {
            productId: "P-07",
            productName: "USB-C Hub",
            category: "Electronics",
            quantity: 2,
            unitPrice: 899,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "Wallet",
          status: "paid",
          paidAt: "2025-01-08T14:01:00Z",
        },
        delivery: {
          estimatedDate: "2025-01-12",
          actualDate: "2025-01-11",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [{ productId: "P-19", rating: 4, helpful: 14, verified: true }],
  },

  {
    customerId: "C009",
    name: "Nisha Gupta",
    email: "nisha.gupta@example.com",
    region: "North",
    tier: "basic",
    joinedAt: "2023-09-05",
    address: { city: "Lucknow", state: "Uttar Pradesh", pincode: "226001" },
    orders: [
      {
        orderId: "ORD-1015",
        placedAt: "2025-03-10T10:00:00Z",
        status: "shipped",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-15",
            productName: "Yoga Mat",
            category: "Sports",
            quantity: 1,
            unitPrice: 899,
            itemStatus: "shipped",
          },
          {
            productId: "P-16",
            productName: "Water Bottle",
            category: "Sports",
            quantity: 1,
            unitPrice: 349,
            itemStatus: "shipped",
          },
        ],
        payment: {
          method: "UPI",
          status: "paid",
          paidAt: "2025-03-10T10:01:00Z",
        },
        delivery: {
          estimatedDate: "2025-03-14",
          actualDate: null,
          deliveredOnTime: null,
        },
      },
    ],
    reviews: [],
  },

  {
    customerId: "C010",
    name: "Rahul Verma",
    email: "rahul.verma@example.com",
    region: "East",
    tier: "premium",
    joinedAt: "2022-02-28",
    address: { city: "Bhubaneswar", state: "Odisha", pincode: "751001" },
    orders: [
      {
        orderId: "ORD-1016",
        placedAt: "2024-12-15T09:00:00Z",
        status: "delivered",
        couponApplied: "FLAT200",
        discountPercent: 7,
        items: [
          {
            productId: "P-20",
            productName: "Smart Watch",
            category: "Electronics",
            quantity: 1,
            unitPrice: 4999,
            itemStatus: "delivered",
          },
          {
            productId: "P-19",
            productName: "Wireless Earbuds",
            category: "Electronics",
            quantity: 1,
            unitPrice: 1499,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "Card",
          status: "paid",
          paidAt: "2024-12-15T09:02:00Z",
        },
        delivery: {
          estimatedDate: "2024-12-19",
          actualDate: "2024-12-18",
          deliveredOnTime: true,
        },
      },
      {
        orderId: "ORD-1017",
        placedAt: "2025-02-05T15:00:00Z",
        status: "delivered",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-08",
            productName: "Clean Code (Book)",
            category: "Books",
            quantity: 3,
            unitPrice: 599,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "UPI",
          status: "paid",
          paidAt: "2025-02-05T15:01:00Z",
        },
        delivery: {
          estimatedDate: "2025-02-09",
          actualDate: "2025-02-11",
          deliveredOnTime: false,
        },
      },
    ],
    reviews: [
      { productId: "P-20", rating: 5, helpful: 20, verified: true },
      { productId: "P-08", rating: 4, helpful: 8, verified: true },
    ],
  },

  {
    customerId: "C011",
    name: "Kavitha Raman",
    email: "kavitha.r@example.com",
    region: "South",
    tier: "enterprise",
    joinedAt: "2021-03-10",
    address: { city: "Coimbatore", state: "Tamil Nadu", pincode: "641001" },
    orders: [
      {
        orderId: "ORD-1018",
        placedAt: "2025-01-20T11:00:00Z",
        status: "delivered",
        couponApplied: "SAVE10",
        discountPercent: 10,
        items: [
          {
            productId: "P-21",
            productName: "Ergonomic Chair",
            category: "Furniture",
            quantity: 4,
            unitPrice: 8999,
            itemStatus: "delivered",
          },
          {
            productId: "P-02",
            productName: "Standing Desk",
            category: "Furniture",
            quantity: 2,
            unitPrice: 12999,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "Card",
          status: "paid",
          paidAt: "2025-01-20T11:05:00Z",
        },
        delivery: {
          estimatedDate: "2025-01-25",
          actualDate: "2025-01-24",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [
      { productId: "P-21", rating: 5, helpful: 53, verified: true },
      { productId: "P-02", rating: 4, helpful: 17, verified: true },
    ],
  },

  {
    customerId: "C012",
    name: "Sanjay Dubey",
    email: "sanjay.d@example.com",
    region: "North",
    tier: "premium",
    joinedAt: "2022-05-30",
    address: { city: "Bhopal", state: "Madhya Pradesh", pincode: "462001" },
    orders: [
      {
        orderId: "ORD-1019",
        placedAt: "2025-02-10T10:00:00Z",
        status: "delivered",
        couponApplied: "FLAT200",
        discountPercent: 5,
        items: [
          {
            productId: "P-03",
            productName: "Mechanical Keyboard",
            category: "Electronics",
            quantity: 3,
            unitPrice: 3499,
            itemStatus: "delivered",
          },
          {
            productId: "P-22",
            productName: "Laptop Stand",
            category: "Electronics",
            quantity: 2,
            unitPrice: 1999,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "UPI",
          status: "paid",
          paidAt: "2025-02-10T10:01:00Z",
        },
        delivery: {
          estimatedDate: "2025-02-14",
          actualDate: "2025-02-13",
          deliveredOnTime: true,
        },
      },
      {
        orderId: "ORD-1020",
        placedAt: "2025-03-05T13:00:00Z",
        status: "processing",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-13",
            productName: "Air Purifier",
            category: "Home",
            quantity: 1,
            unitPrice: 7999,
            itemStatus: "processing",
          },
        ],
        payment: {
          method: "Card",
          status: "paid",
          paidAt: "2025-03-05T13:02:00Z",
        },
        delivery: {
          estimatedDate: "2025-03-09",
          actualDate: null,
          deliveredOnTime: null,
        },
      },
    ],
    reviews: [{ productId: "P-03", rating: 5, helpful: 31, verified: true }],
  },

  {
    customerId: "C013",
    name: "Pooja Iyer",
    email: "pooja.iyer@example.com",
    region: "West",
    tier: "basic",
    joinedAt: "2023-03-20",
    address: { city: "Pune", state: "Maharashtra", pincode: "411001" },
    orders: [
      {
        orderId: "ORD-1021",
        placedAt: "2025-01-25T09:00:00Z",
        status: "delivered",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-09",
            productName: "You Don't Know JS",
            category: "Books",
            quantity: 2,
            unitPrice: 499,
            itemStatus: "delivered",
          },
          {
            productId: "P-15",
            productName: "Yoga Mat",
            category: "Sports",
            quantity: 1,
            unitPrice: 899,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "COD",
          status: "paid",
          paidAt: "2025-01-28T11:00:00Z",
        },
        delivery: {
          estimatedDate: "2025-01-29",
          actualDate: "2025-01-28",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [{ productId: "P-09", rating: 5, helpful: 16, verified: true }],
  },

  {
    customerId: "C014",
    name: "Arun Pillai",
    email: "arun.pillai@example.com",
    region: "East",
    tier: "premium",
    joinedAt: "2021-10-10",
    address: { city: "Guwahati", state: "Assam", pincode: "781001" },
    orders: [
      {
        orderId: "ORD-1022",
        placedAt: "2025-02-22T16:00:00Z",
        status: "delivered",
        couponApplied: "SAVE10",
        discountPercent: 10,
        items: [
          {
            productId: "P-20",
            productName: "Smart Watch",
            category: "Electronics",
            quantity: 2,
            unitPrice: 4999,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "Wallet",
          status: "paid",
          paidAt: "2025-02-22T16:01:00Z",
        },
        delivery: {
          estimatedDate: "2025-02-26",
          actualDate: "2025-02-28",
          deliveredOnTime: false,
        },
      },
      {
        orderId: "ORD-1078",
        placedAt: "2025-03-15T08:00:00Z",
        status: "processing",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-07",
            productName: "USB-C Hub",
            category: "Electronics",
            quantity: 3,
            unitPrice: 899,
            itemStatus: "processing",
          },
        ],
        payment: { method: "Card", status: "failed", paidAt: null },
        delivery: {
          estimatedDate: "2025-03-19",
          actualDate: null,
          deliveredOnTime: null,
        },
      },
    ],
    reviews: [{ productId: "P-20", rating: 4, helpful: 9, verified: true }],
  },

  {
    customerId: "C015",
    name: "Geeta Sharma",
    email: "geeta.sharma@example.com",
    region: "North",
    tier: "basic",
    joinedAt: "2023-11-01",
    address: { city: "Chandigarh", state: "Punjab", pincode: "160001" },
    orders: [
      {
        orderId: "ORD-1023",
        placedAt: "2025-03-01T10:00:00Z",
        status: "delivered",
        couponApplied: "FLAT200",
        discountPercent: 5,
        items: [
          {
            productId: "P-12",
            productName: "Desk Lamp",
            category: "Home",
            quantity: 2,
            unitPrice: 1299,
            itemStatus: "delivered",
          },
          {
            productId: "P-16",
            productName: "Water Bottle",
            category: "Sports",
            quantity: 3,
            unitPrice: 349,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "UPI",
          status: "paid",
          paidAt: "2025-03-01T10:01:00Z",
        },
        delivery: {
          estimatedDate: "2025-03-05",
          actualDate: "2025-03-04",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [],
  },

  {
    customerId: "C016",
    name: "Harish Kumar",
    email: "harish.k@example.com",
    region: "South",
    tier: "premium",
    joinedAt: "2022-09-14",
    address: { city: "Mysore", state: "Karnataka", pincode: "570001" },
    orders: [
      {
        orderId: "ORD-1024",
        placedAt: "2025-01-30T14:00:00Z",
        status: "delivered",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-19",
            productName: "Wireless Earbuds",
            category: "Electronics",
            quantity: 2,
            unitPrice: 1499,
            itemStatus: "delivered",
          },
          {
            productId: "P-13",
            productName: "Air Purifier",
            category: "Home",
            quantity: 1,
            unitPrice: 7999,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "Card",
          status: "paid",
          paidAt: "2025-01-30T14:02:00Z",
        },
        delivery: {
          estimatedDate: "2025-02-03",
          actualDate: "2025-02-03",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [{ productId: "P-13", rating: 4, helpful: 22, verified: true }],
  },

  {
    customerId: "C017",
    name: "Tanvi Desai",
    email: "tanvi.desai@example.com",
    region: "West",
    tier: "enterprise",
    joinedAt: "2020-07-22",
    address: { city: "Surat", state: "Gujarat", pincode: "395001" },
    orders: [
      {
        orderId: "ORD-1025",
        placedAt: "2024-12-10T09:00:00Z",
        status: "delivered",
        couponApplied: "SAVE10",
        discountPercent: 10,
        items: [
          {
            productId: "P-21",
            productName: "Ergonomic Chair",
            category: "Furniture",
            quantity: 6,
            unitPrice: 8999,
            itemStatus: "delivered",
          },
          {
            productId: "P-11",
            productName: "Monitor Arm",
            category: "Furniture",
            quantity: 4,
            unitPrice: 2499,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "Card",
          status: "paid",
          paidAt: "2024-12-10T09:05:00Z",
        },
        delivery: {
          estimatedDate: "2024-12-15",
          actualDate: "2024-12-14",
          deliveredOnTime: true,
        },
      },
      {
        orderId: "ORD-1026",
        placedAt: "2025-02-28T11:00:00Z",
        status: "delivered",
        couponApplied: "FLAT200",
        discountPercent: 8,
        items: [
          {
            productId: "P-03",
            productName: "Mechanical Keyboard",
            category: "Electronics",
            quantity: 5,
            unitPrice: 3499,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "Card",
          status: "paid",
          paidAt: "2025-02-28T11:02:00Z",
        },
        delivery: {
          estimatedDate: "2025-03-04",
          actualDate: "2025-03-06",
          deliveredOnTime: false,
        },
      },
    ],
    reviews: [
      { productId: "P-21", rating: 5, helpful: 61, verified: true },
      { productId: "P-03", rating: 4, helpful: 19, verified: true },
    ],
  },

  {
    customerId: "C018",
    name: "Nikhil Bose",
    email: "nikhil.bose@example.com",
    region: "East",
    tier: "basic",
    joinedAt: "2023-04-18",
    address: { city: "Patna", state: "Bihar", pincode: "800001" },
    orders: [
      {
        orderId: "ORD-1027",
        placedAt: "2025-01-12T08:00:00Z",
        status: "delivered",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-15",
            productName: "Yoga Mat",
            category: "Sports",
            quantity: 2,
            unitPrice: 899,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "COD",
          status: "paid",
          paidAt: "2025-01-15T10:00:00Z",
        },
        delivery: {
          estimatedDate: "2025-01-16",
          actualDate: "2025-01-17",
          deliveredOnTime: false,
        },
      },
    ],
    reviews: [{ productId: "P-15", rating: 3, helpful: 4, verified: true }],
  },

  {
    customerId: "C019",
    name: "Divya Menon",
    email: "divya.menon@example.com",
    region: "South",
    tier: "basic",
    joinedAt: "2023-07-07",
    address: { city: "Kochi", state: "Kerala", pincode: "682001" },
    orders: [
      {
        orderId: "ORD-1028",
        placedAt: "2025-01-03T11:00:00Z",
        status: "pending",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-12",
            productName: "Desk Lamp",
            category: "Home",
            quantity: 1,
            unitPrice: 1299,
            itemStatus: "pending",
          },
        ],
        payment: { method: "UPI", status: "pending", paidAt: null },
        delivery: {
          estimatedDate: "2025-01-07",
          actualDate: null,
          deliveredOnTime: null,
        },
      },
    ],
    reviews: [],
  },

  {
    customerId: "C020",
    name: "Rohit Saxena",
    email: "rohit.saxena@example.com",
    region: "North",
    tier: "enterprise",
    joinedAt: "2021-01-19",
    address: { city: "Noida", state: "Uttar Pradesh", pincode: "201301" },
    orders: [
      {
        orderId: "ORD-1029",
        placedAt: "2025-02-15T10:00:00Z",
        status: "delivered",
        couponApplied: "SAVE10",
        discountPercent: 10,
        items: [
          {
            productId: "P-02",
            productName: "Standing Desk",
            category: "Furniture",
            quantity: 3,
            unitPrice: 12999,
            itemStatus: "delivered",
          },
          {
            productId: "P-21",
            productName: "Ergonomic Chair",
            category: "Furniture",
            quantity: 3,
            unitPrice: 8999,
            itemStatus: "delivered",
          },
          {
            productId: "P-07",
            productName: "USB-C Hub",
            category: "Electronics",
            quantity: 5,
            unitPrice: 899,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "Card",
          status: "paid",
          paidAt: "2025-02-15T10:05:00Z",
        },
        delivery: {
          estimatedDate: "2025-02-20",
          actualDate: "2025-02-19",
          deliveredOnTime: true,
        },
      },
      {
        orderId: "ORD-1030",
        placedAt: "2025-03-18T09:00:00Z",
        status: "shipped",
        couponApplied: "FLAT200",
        discountPercent: 6,
        items: [
          {
            productId: "P-20",
            productName: "Smart Watch",
            category: "Electronics",
            quantity: 4,
            unitPrice: 4999,
            itemStatus: "shipped",
          },
        ],
        payment: {
          method: "Card",
          status: "paid",
          paidAt: "2025-03-18T09:02:00Z",
        },
        delivery: {
          estimatedDate: "2025-03-22",
          actualDate: null,
          deliveredOnTime: null,
        },
      },
    ],
    reviews: [
      { productId: "P-02", rating: 5, helpful: 38, verified: true },
      { productId: "P-21", rating: 5, helpful: 27, verified: true },
    ],
  },

  // ---- Customers C021–C041: mix of regions/tiers, sparser orders ----

  {
    customerId: "C021",
    name: "Ishaan Bajaj",
    email: "ishaan.b@example.com",
    region: "West",
    tier: "basic",
    joinedAt: "2023-02-10",
    address: { city: "Vadodara", state: "Gujarat", pincode: "390001" },
    orders: [
      {
        orderId: "ORD-1031",
        placedAt: "2025-01-18T10:00:00Z",
        status: "delivered",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-09",
            productName: "You Don't Know JS",
            category: "Books",
            quantity: 2,
            unitPrice: 499,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "COD",
          status: "paid",
          paidAt: "2025-01-21T10:00:00Z",
        },
        delivery: {
          estimatedDate: "2025-01-22",
          actualDate: "2025-01-21",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [{ productId: "P-09", rating: 5, helpful: 7, verified: true }],
  },
  {
    customerId: "C022",
    name: "Swati Kulkarni",
    email: "swati.k@example.com",
    region: "West",
    tier: "premium",
    joinedAt: "2022-04-05",
    address: { city: "Nagpur", state: "Maharashtra", pincode: "440001" },
    orders: [
      {
        orderId: "ORD-1032",
        placedAt: "2025-02-08T14:00:00Z",
        status: "delivered",
        couponApplied: "SAVE10",
        discountPercent: 10,
        items: [
          {
            productId: "P-03",
            productName: "Mechanical Keyboard",
            category: "Electronics",
            quantity: 1,
            unitPrice: 3499,
            itemStatus: "delivered",
          },
          {
            productId: "P-22",
            productName: "Laptop Stand",
            category: "Electronics",
            quantity: 1,
            unitPrice: 1999,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "UPI",
          status: "paid",
          paidAt: "2025-02-08T14:01:00Z",
        },
        delivery: {
          estimatedDate: "2025-02-12",
          actualDate: "2025-02-11",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [{ productId: "P-03", rating: 4, helpful: 10, verified: true }],
  },
  {
    customerId: "C023",
    name: "Manish Tiwari",
    email: "manish.t@example.com",
    region: "North",
    tier: "basic",
    joinedAt: "2023-08-19",
    address: { city: "Agra", state: "Uttar Pradesh", pincode: "282001" },
    orders: [
      {
        orderId: "ORD-1034",
        placedAt: "2025-03-02T09:00:00Z",
        status: "delivered",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-16",
            productName: "Water Bottle",
            category: "Sports",
            quantity: 4,
            unitPrice: 349,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "COD",
          status: "paid",
          paidAt: "2025-03-05T10:00:00Z",
        },
        delivery: {
          estimatedDate: "2025-03-06",
          actualDate: "2025-03-05",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [],
  },
  {
    customerId: "C024",
    name: "Rekha Nandan",
    email: "rekha.n@example.com",
    region: "East",
    tier: "premium",
    joinedAt: "2022-06-12",
    address: { city: "Ranchi", state: "Jharkhand", pincode: "834001" },
    orders: [
      {
        orderId: "ORD-1035",
        placedAt: "2025-01-22T15:00:00Z",
        status: "delivered",
        couponApplied: "FLAT200",
        discountPercent: 5,
        items: [
          {
            productId: "P-20",
            productName: "Smart Watch",
            category: "Electronics",
            quantity: 1,
            unitPrice: 4999,
            itemStatus: "delivered",
          },
          {
            productId: "P-19",
            productName: "Wireless Earbuds",
            category: "Electronics",
            quantity: 2,
            unitPrice: 1499,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "Card",
          status: "paid",
          paidAt: "2025-01-22T15:02:00Z",
        },
        delivery: {
          estimatedDate: "2025-01-26",
          actualDate: "2025-01-25",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [{ productId: "P-20", rating: 5, helpful: 15, verified: true }],
  },
  {
    customerId: "C025",
    name: "Vinod Chandra",
    email: "vinod.c@example.com",
    region: "South",
    tier: "enterprise",
    joinedAt: "2020-11-30",
    address: { city: "Vijayawada", state: "Andhra Pradesh", pincode: "520001" },
    orders: [
      {
        orderId: "ORD-1036",
        placedAt: "2025-01-10T11:00:00Z",
        status: "delivered",
        couponApplied: "SAVE10",
        discountPercent: 10,
        items: [
          {
            productId: "P-02",
            productName: "Standing Desk",
            category: "Furniture",
            quantity: 2,
            unitPrice: 12999,
            itemStatus: "delivered",
          },
          {
            productId: "P-11",
            productName: "Monitor Arm",
            category: "Furniture",
            quantity: 3,
            unitPrice: 2499,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "Card",
          status: "paid",
          paidAt: "2025-01-10T11:05:00Z",
        },
        delivery: {
          estimatedDate: "2025-01-15",
          actualDate: "2025-01-14",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [
      { productId: "P-02", rating: 5, helpful: 45, verified: true },
      { productId: "P-11", rating: 4, helpful: 12, verified: true },
    ],
  },
  {
    customerId: "C026",
    name: "Anjali Bhatt",
    email: "anjali.b@example.com",
    region: "West",
    tier: "basic",
    joinedAt: "2023-05-25",
    address: { city: "Rajkot", state: "Gujarat", pincode: "360001" },
    orders: [
      {
        orderId: "ORD-1037",
        placedAt: "2025-02-20T10:00:00Z",
        status: "delivered",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-15",
            productName: "Yoga Mat",
            category: "Sports",
            quantity: 1,
            unitPrice: 899,
            itemStatus: "delivered",
          },
          {
            productId: "P-08",
            productName: "Clean Code (Book)",
            category: "Books",
            quantity: 1,
            unitPrice: 599,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "COD",
          status: "paid",
          paidAt: "2025-02-23T11:00:00Z",
        },
        delivery: {
          estimatedDate: "2025-02-24",
          actualDate: "2025-02-23",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [{ productId: "P-08", rating: 4, helpful: 5, verified: true }],
  },
  {
    customerId: "C027",
    name: "Kartik Mishra",
    email: "kartik.m@example.com",
    region: "North",
    tier: "premium",
    joinedAt: "2022-01-15",
    address: { city: "Varanasi", state: "Uttar Pradesh", pincode: "221001" },
    orders: [
      {
        orderId: "ORD-1038",
        placedAt: "2025-01-28T14:00:00Z",
        status: "delivered",
        couponApplied: "FLAT200",
        discountPercent: 5,
        items: [
          {
            productId: "P-03",
            productName: "Mechanical Keyboard",
            category: "Electronics",
            quantity: 2,
            unitPrice: 3499,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "UPI",
          status: "paid",
          paidAt: "2025-01-28T14:01:00Z",
        },
        delivery: {
          estimatedDate: "2025-02-01",
          actualDate: "2025-01-31",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [{ productId: "P-03", rating: 5, helpful: 23, verified: true }],
  },
  {
    customerId: "C028",
    name: "Lata Pandey",
    email: "lata.p@example.com",
    region: "East",
    tier: "basic",
    joinedAt: "2023-10-02",
    address: { city: "Dhanbad", state: "Jharkhand", pincode: "826001" },
    orders: [
      {
        orderId: "ORD-1039",
        placedAt: "2025-02-12T09:00:00Z",
        status: "cancelled",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-12",
            productName: "Desk Lamp",
            category: "Home",
            quantity: 1,
            unitPrice: 1299,
            itemStatus: "cancelled",
          },
        ],
        payment: {
          method: "UPI",
          status: "refunded",
          paidAt: "2025-02-12T09:01:00Z",
        },
        delivery: {
          estimatedDate: null,
          actualDate: null,
          deliveredOnTime: null,
        },
      },
    ],
    reviews: [],
  },
  {
    customerId: "C029",
    name: "Suresh Negi",
    email: "suresh.n@example.com",
    region: "North",
    tier: "premium",
    joinedAt: "2022-08-08",
    address: { city: "Dehradun", state: "Uttarakhand", pincode: "248001" },
    orders: [
      {
        orderId: "ORD-1040",
        placedAt: "2025-03-08T11:00:00Z",
        status: "delivered",
        couponApplied: "SAVE10",
        discountPercent: 10,
        items: [
          {
            productId: "P-22",
            productName: "Laptop Stand",
            category: "Electronics",
            quantity: 3,
            unitPrice: 1999,
            itemStatus: "delivered",
          },
          {
            productId: "P-07",
            productName: "USB-C Hub",
            category: "Electronics",
            quantity: 2,
            unitPrice: 899,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "Card",
          status: "paid",
          paidAt: "2025-03-08T11:02:00Z",
        },
        delivery: {
          estimatedDate: "2025-03-12",
          actualDate: "2025-03-11",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [{ productId: "P-22", rating: 4, helpful: 8, verified: true }],
  },
  {
    customerId: "C030",
    name: "Poonam Awasthi",
    email: "poonam.a@example.com",
    region: "South",
    tier: "basic",
    joinedAt: "2023-12-01",
    address: { city: "Thrissur", state: "Kerala", pincode: "680001" },
    orders: [
      {
        orderId: "ORD-1041",
        placedAt: "2025-03-15T10:00:00Z",
        status: "processing",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-09",
            productName: "You Don't Know JS",
            category: "Books",
            quantity: 1,
            unitPrice: 499,
            itemStatus: "processing",
          },
        ],
        payment: {
          method: "UPI",
          status: "paid",
          paidAt: "2025-03-15T10:01:00Z",
        },
        delivery: {
          estimatedDate: "2025-03-19",
          actualDate: null,
          deliveredOnTime: null,
        },
      },
    ],
    reviews: [],
  },
  {
    customerId: "C031",
    name: "Ravi Shankar",
    email: "ravi.s@example.com",
    region: "West",
    tier: "premium",
    joinedAt: "2021-09-09",
    address: { city: "Thane", state: "Maharashtra", pincode: "400601" },
    orders: [
      {
        orderId: "ORD-1042",
        placedAt: "2025-02-05T15:00:00Z",
        status: "delivered",
        couponApplied: "FLAT200",
        discountPercent: 8,
        items: [
          {
            productId: "P-19",
            productName: "Wireless Earbuds",
            category: "Electronics",
            quantity: 3,
            unitPrice: 1499,
            itemStatus: "delivered",
          },
          {
            productId: "P-20",
            productName: "Smart Watch",
            category: "Electronics",
            quantity: 1,
            unitPrice: 4999,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "Wallet",
          status: "paid",
          paidAt: "2025-02-05T15:01:00Z",
        },
        delivery: {
          estimatedDate: "2025-02-09",
          actualDate: "2025-02-09",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [
      { productId: "P-19", rating: 4, helpful: 13, verified: true },
      { productId: "P-20", rating: 4, helpful: 6, verified: true },
    ],
  },
  {
    customerId: "C032",
    name: "Shreya Banerjee",
    email: "shreya.b@example.com",
    region: "East",
    tier: "enterprise",
    joinedAt: "2020-04-14",
    address: { city: "Durgapur", state: "West Bengal", pincode: "713201" },
    orders: [
      {
        orderId: "ORD-1043",
        placedAt: "2025-01-15T09:00:00Z",
        status: "delivered",
        couponApplied: "SAVE10",
        discountPercent: 10,
        items: [
          {
            productId: "P-21",
            productName: "Ergonomic Chair",
            category: "Furniture",
            quantity: 3,
            unitPrice: 8999,
            itemStatus: "delivered",
          },
          {
            productId: "P-02",
            productName: "Standing Desk",
            category: "Furniture",
            quantity: 1,
            unitPrice: 12999,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "Card",
          status: "paid",
          paidAt: "2025-01-15T09:05:00Z",
        },
        delivery: {
          estimatedDate: "2025-01-20",
          actualDate: "2025-01-19",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [{ productId: "P-21", rating: 5, helpful: 39, verified: true }],
  },
  {
    customerId: "C033",
    name: "Amit Ghosh",
    email: "amit.g@example.com",
    region: "East",
    tier: "basic",
    joinedAt: "2023-02-28",
    address: { city: "Siliguri", state: "West Bengal", pincode: "734001" },
    orders: [
      {
        orderId: "ORD-1045",
        placedAt: "2025-02-28T10:00:00Z",
        status: "shipped",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-16",
            productName: "Water Bottle",
            category: "Sports",
            quantity: 2,
            unitPrice: 349,
            itemStatus: "shipped",
          },
        ],
        payment: {
          method: "COD",
          status: "paid",
          paidAt: "2025-03-03T11:00:00Z",
        },
        delivery: {
          estimatedDate: "2025-03-04",
          actualDate: null,
          deliveredOnTime: null,
        },
      },
    ],
    reviews: [],
  },
  {
    customerId: "C034",
    name: "Pallavi Jain",
    email: "pallavi.j@example.com",
    region: "West",
    tier: "enterprise",
    joinedAt: "2020-06-11",
    address: { city: "Indore", state: "Madhya Pradesh", pincode: "452001" },
    orders: [
      {
        orderId: "ORD-1046",
        placedAt: "2025-01-08T11:00:00Z",
        status: "delivered",
        couponApplied: "SAVE10",
        discountPercent: 10,
        items: [
          {
            productId: "P-02",
            productName: "Standing Desk",
            category: "Furniture",
            quantity: 2,
            unitPrice: 12999,
            itemStatus: "delivered",
          },
          {
            productId: "P-21",
            productName: "Ergonomic Chair",
            category: "Furniture",
            quantity: 4,
            unitPrice: 8999,
            itemStatus: "delivered",
          },
          {
            productId: "P-03",
            productName: "Mechanical Keyboard",
            category: "Electronics",
            quantity: 2,
            unitPrice: 3499,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "Card",
          status: "paid",
          paidAt: "2025-01-08T11:06:00Z",
        },
        delivery: {
          estimatedDate: "2025-01-13",
          actualDate: "2025-01-12",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [
      { productId: "P-02", rating: 5, helpful: 52, verified: true },
      { productId: "P-21", rating: 5, helpful: 44, verified: true },
    ],
  },
  {
    customerId: "C035",
    name: "Balu Reddy",
    email: "balu.r@example.com",
    region: "South",
    tier: "premium",
    joinedAt: "2022-03-03",
    address: { city: "Tirupati", state: "Andhra Pradesh", pincode: "517501" },
    orders: [
      {
        orderId: "ORD-1047",
        placedAt: "2025-02-10T09:00:00Z",
        status: "delivered",
        couponApplied: "FLAT200",
        discountPercent: 6,
        items: [
          {
            productId: "P-13",
            productName: "Air Purifier",
            category: "Home",
            quantity: 2,
            unitPrice: 7999,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "Card",
          status: "paid",
          paidAt: "2025-02-10T09:03:00Z",
        },
        delivery: {
          estimatedDate: "2025-02-14",
          actualDate: "2025-02-14",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [{ productId: "P-13", rating: 5, helpful: 18, verified: true }],
  },
  {
    customerId: "C036",
    name: "Hema Sundaram",
    email: "hema.s@example.com",
    region: "South",
    tier: "basic",
    joinedAt: "2023-09-20",
    address: { city: "Salem", state: "Tamil Nadu", pincode: "636001" },
    orders: [
      {
        orderId: "ORD-1048",
        placedAt: "2025-03-10T08:00:00Z",
        status: "pending",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-15",
            productName: "Yoga Mat",
            category: "Sports",
            quantity: 1,
            unitPrice: 899,
            itemStatus: "pending",
          },
        ],
        payment: { method: "COD", status: "pending", paidAt: null },
        delivery: {
          estimatedDate: "2025-03-14",
          actualDate: null,
          deliveredOnTime: null,
        },
      },
    ],
    reviews: [],
  },
  {
    customerId: "C037",
    name: "Gaurav Kapoor",
    email: "gaurav.k@example.com",
    region: "North",
    tier: "basic",
    joinedAt: "2023-07-14",
    address: { city: "Meerut", state: "Uttar Pradesh", pincode: "250001" },
    orders: [
      {
        orderId: "ORD-1049",
        placedAt: "2025-01-20T13:00:00Z",
        status: "delivered",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-08",
            productName: "Clean Code (Book)",
            category: "Books",
            quantity: 1,
            unitPrice: 599,
            itemStatus: "delivered",
          },
          {
            productId: "P-09",
            productName: "You Don't Know JS",
            category: "Books",
            quantity: 1,
            unitPrice: 499,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "UPI",
          status: "paid",
          paidAt: "2025-01-20T13:01:00Z",
        },
        delivery: {
          estimatedDate: "2025-01-24",
          actualDate: "2025-01-24",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [
      { productId: "P-08", rating: 5, helpful: 11, verified: true },
      { productId: "P-09", rating: 4, helpful: 6, verified: true },
    ],
  },
  {
    customerId: "C038",
    name: "Nalini Varma",
    email: "nalini.v@example.com",
    region: "East",
    tier: "premium",
    joinedAt: "2022-10-20",
    address: {
      city: "Visakhapatnam",
      state: "Andhra Pradesh",
      pincode: "530001",
    },
    orders: [
      {
        orderId: "ORD-1050",
        placedAt: "2025-02-25T14:00:00Z",
        status: "delivered",
        couponApplied: "SAVE10",
        discountPercent: 10,
        items: [
          {
            productId: "P-19",
            productName: "Wireless Earbuds",
            category: "Electronics",
            quantity: 2,
            unitPrice: 1499,
            itemStatus: "delivered",
          },
          {
            productId: "P-22",
            productName: "Laptop Stand",
            category: "Electronics",
            quantity: 2,
            unitPrice: 1999,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "UPI",
          status: "paid",
          paidAt: "2025-02-25T14:01:00Z",
        },
        delivery: {
          estimatedDate: "2025-03-01",
          actualDate: "2025-02-28",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [{ productId: "P-19", rating: 5, helpful: 16, verified: true }],
  },
  {
    customerId: "C039",
    name: "Dinesh Choudhary",
    email: "dinesh.c@example.com",
    region: "North",
    tier: "enterprise",
    joinedAt: "2021-06-06",
    address: { city: "Jodhpur", state: "Rajasthan", pincode: "342001" },
    orders: [
      {
        orderId: "ORD-1051",
        placedAt: "2025-03-05T10:00:00Z",
        status: "delivered",
        couponApplied: "FLAT200",
        discountPercent: 8,
        items: [
          {
            productId: "P-02",
            productName: "Standing Desk",
            category: "Furniture",
            quantity: 2,
            unitPrice: 12999,
            itemStatus: "delivered",
          },
          {
            productId: "P-07",
            productName: "USB-C Hub",
            category: "Electronics",
            quantity: 6,
            unitPrice: 899,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "Card",
          status: "paid",
          paidAt: "2025-03-05T10:04:00Z",
        },
        delivery: {
          estimatedDate: "2025-03-09",
          actualDate: "2025-03-10",
          deliveredOnTime: false,
        },
      },
    ],
    reviews: [{ productId: "P-02", rating: 4, helpful: 24, verified: true }],
  },
  {
    customerId: "C040",
    name: "Shalini Iyer",
    email: "shalini.i@example.com",
    region: "South",
    tier: "premium",
    joinedAt: "2022-12-12",
    address: { city: "Madurai", state: "Tamil Nadu", pincode: "625001" },
    orders: [
      {
        orderId: "ORD-1052",
        placedAt: "2025-01-28T09:00:00Z",
        status: "delivered",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-11",
            productName: "Monitor Arm",
            category: "Furniture",
            quantity: 2,
            unitPrice: 2499,
            itemStatus: "delivered",
          },
          {
            productId: "P-12",
            productName: "Desk Lamp",
            category: "Home",
            quantity: 1,
            unitPrice: 1299,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "Card",
          status: "paid",
          paidAt: "2025-01-28T09:02:00Z",
        },
        delivery: {
          estimatedDate: "2025-02-01",
          actualDate: "2025-02-01",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [{ productId: "P-11", rating: 4, helpful: 9, verified: true }],
  },

  // C041 — no orders (churn + no-order test case)
  {
    customerId: "C041",
    name: "Sneha Roy",
    email: "sneha.roy@example.com",
    region: "East",
    tier: "basic",
    joinedAt: "2024-01-05",
    address: { city: "Asansol", state: "West Bengal", pincode: "713301" },
    orders: [],
    reviews: [],
  },

  {
    customerId: "C042",
    name: "Prakash Yadav",
    email: "prakash.y@example.com",
    region: "North",
    tier: "basic",
    joinedAt: "2023-11-11",
    address: { city: "Allahabad", state: "Uttar Pradesh", pincode: "211001" },
    orders: [
      {
        orderId: "ORD-1053",
        placedAt: "2025-02-18T10:00:00Z",
        status: "delivered",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-16",
            productName: "Water Bottle",
            category: "Sports",
            quantity: 5,
            unitPrice: 349,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "COD",
          status: "paid",
          paidAt: "2025-02-21T10:00:00Z",
        },
        delivery: {
          estimatedDate: "2025-02-22",
          actualDate: "2025-02-21",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [],
  },
  {
    customerId: "C043",
    name: "Archana Pillai",
    email: "archana.p@example.com",
    region: "South",
    tier: "premium",
    joinedAt: "2022-02-14",
    address: { city: "Kozhikode", state: "Kerala", pincode: "673001" },
    orders: [
      {
        orderId: "ORD-1054",
        placedAt: "2025-03-12T11:00:00Z",
        status: "shipped",
        couponApplied: "SAVE10",
        discountPercent: 10,
        items: [
          {
            productId: "P-20",
            productName: "Smart Watch",
            category: "Electronics",
            quantity: 2,
            unitPrice: 4999,
            itemStatus: "shipped",
          },
        ],
        payment: {
          method: "UPI",
          status: "paid",
          paidAt: "2025-03-12T11:01:00Z",
        },
        delivery: {
          estimatedDate: "2025-03-16",
          actualDate: null,
          deliveredOnTime: null,
        },
      },
    ],
    reviews: [],
  },
  {
    customerId: "C044",
    name: "Manoj Tomar",
    email: "manoj.t@example.com",
    region: "East",
    tier: "basic",
    joinedAt: "2024-02-20",
    address: { city: "Jamshedpur", state: "Jharkhand", pincode: "831001" },
    orders: [
      {
        orderId: "ORD-1055",
        placedAt: "2025-01-30T15:00:00Z",
        status: "delivered",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-08",
            productName: "Clean Code (Book)",
            category: "Books",
            quantity: 1,
            unitPrice: 599,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "COD",
          status: "paid",
          paidAt: "2025-02-02T10:00:00Z",
        },
        delivery: {
          estimatedDate: "2025-02-03",
          actualDate: "2025-02-02",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [{ productId: "P-08", rating: 4, helpful: 3, verified: false }],
  },
  {
    customerId: "C045",
    name: "Usha Kiran",
    email: "usha.k@example.com",
    region: "West",
    tier: "enterprise",
    joinedAt: "2020-09-25",
    address: { city: "Nashik", state: "Maharashtra", pincode: "422001" },
    orders: [
      {
        orderId: "ORD-1056",
        placedAt: "2025-02-22T10:00:00Z",
        status: "delivered",
        couponApplied: "FLAT200",
        discountPercent: 10,
        items: [
          {
            productId: "P-21",
            productName: "Ergonomic Chair",
            category: "Furniture",
            quantity: 5,
            unitPrice: 8999,
            itemStatus: "delivered",
          },
          {
            productId: "P-11",
            productName: "Monitor Arm",
            category: "Furniture",
            quantity: 5,
            unitPrice: 2499,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "Card",
          status: "paid",
          paidAt: "2025-02-22T10:05:00Z",
        },
        delivery: {
          estimatedDate: "2025-02-26",
          actualDate: "2025-02-25",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [{ productId: "P-21", rating: 5, helpful: 47, verified: true }],
  },
  {
    customerId: "C046",
    name: "Bhavesh Patel",
    email: "bhavesh.p@example.com",
    region: "West",
    tier: "basic",
    joinedAt: "2023-06-30",
    address: { city: "Anand", state: "Gujarat", pincode: "388001" },
    orders: [
      {
        orderId: "ORD-1057",
        placedAt: "2025-01-16T09:00:00Z",
        status: "delivered",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-15",
            productName: "Yoga Mat",
            category: "Sports",
            quantity: 2,
            unitPrice: 899,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "UPI",
          status: "paid",
          paidAt: "2025-01-16T09:01:00Z",
        },
        delivery: {
          estimatedDate: "2025-01-20",
          actualDate: "2025-01-20",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [],
  },
  {
    customerId: "C047",
    name: "Deepak Tripathi",
    email: "deepak.tri@example.com",
    region: "North",
    tier: "premium",
    joinedAt: "2022-07-07",
    address: { city: "Gwalior", state: "Madhya Pradesh", pincode: "474001" },
    orders: [
      {
        orderId: "ORD-1058",
        placedAt: "2025-03-14T14:00:00Z",
        status: "processing",
        couponApplied: "SAVE10",
        discountPercent: 10,
        items: [
          {
            productId: "P-03",
            productName: "Mechanical Keyboard",
            category: "Electronics",
            quantity: 1,
            unitPrice: 3499,
            itemStatus: "processing",
          },
          {
            productId: "P-22",
            productName: "Laptop Stand",
            category: "Electronics",
            quantity: 2,
            unitPrice: 1999,
            itemStatus: "processing",
          },
        ],
        payment: {
          method: "Card",
          status: "paid",
          paidAt: "2025-03-14T14:02:00Z",
        },
        delivery: {
          estimatedDate: "2025-03-18",
          actualDate: null,
          deliveredOnTime: null,
        },
      },
    ],
    reviews: [],
  },
  {
    customerId: "C048",
    name: "Chitra Selvam",
    email: "chitra.s@example.com",
    region: "South",
    tier: "enterprise",
    joinedAt: "2021-04-18",
    address: {
      city: "Tiruchirappalli",
      state: "Tamil Nadu",
      pincode: "620001",
    },
    orders: [
      {
        orderId: "ORD-1059",
        placedAt: "2025-01-12T10:00:00Z",
        status: "delivered",
        couponApplied: "FLAT200",
        discountPercent: 10,
        items: [
          {
            productId: "P-02",
            productName: "Standing Desk",
            category: "Furniture",
            quantity: 3,
            unitPrice: 12999,
            itemStatus: "delivered",
          },
          {
            productId: "P-13",
            productName: "Air Purifier",
            category: "Home",
            quantity: 2,
            unitPrice: 7999,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "Card",
          status: "paid",
          paidAt: "2025-01-12T10:05:00Z",
        },
        delivery: {
          estimatedDate: "2025-01-17",
          actualDate: "2025-01-16",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [
      { productId: "P-02", rating: 5, helpful: 36, verified: true },
      { productId: "P-13", rating: 4, helpful: 14, verified: true },
    ],
  },
  {
    customerId: "C049",
    name: "Rajesh Nambiar",
    email: "rajesh.n@example.com",
    region: "East",
    tier: "premium",
    joinedAt: "2022-08-30",
    address: { city: "Cuttack", state: "Odisha", pincode: "753001" },
    orders: [
      {
        orderId: "ORD-1060",
        placedAt: "2025-02-15T13:00:00Z",
        status: "delivered",
        couponApplied: null,
        discountPercent: 0,
        items: [
          {
            productId: "P-19",
            productName: "Wireless Earbuds",
            category: "Electronics",
            quantity: 3,
            unitPrice: 1499,
            itemStatus: "delivered",
          },
          {
            productId: "P-07",
            productName: "USB-C Hub",
            category: "Electronics",
            quantity: 2,
            unitPrice: 899,
            itemStatus: "delivered",
          },
        ],
        payment: {
          method: "UPI",
          status: "paid",
          paidAt: "2025-02-15T13:01:00Z",
        },
        delivery: {
          estimatedDate: "2025-02-19",
          actualDate: "2025-02-19",
          deliveredOnTime: true,
        },
      },
    ],
    reviews: [{ productId: "P-19", rating: 4, helpful: 10, verified: true }],
  },
  {
    customerId: "C050",
    name: "Kavya Subramaniam",
    email: "kavya.sub@example.com",
    region: "South",
    tier: "premium",
    joinedAt: "2022-05-05",
    address: { city: "Pondicherry", state: "Puducherry", pincode: "605001" },
    orders: [
      {
        orderId: "ORD-1061",
        placedAt: "2025-03-20T10:00:00Z",
        status: "pending",
        couponApplied: "SAVE10",
        discountPercent: 10,
        items: [
          {
            productId: "P-20",
            productName: "Smart Watch",
            category: "Electronics",
            quantity: 1,
            unitPrice: 4999,
            itemStatus: "pending",
          },
          {
            productId: "P-12",
            productName: "Desk Lamp",
            category: "Home",
            quantity: 2,
            unitPrice: 1299,
            itemStatus: "pending",
          },
        ],
        payment: { method: "Card", status: "pending", paidAt: null },
        delivery: {
          estimatedDate: "2025-03-24",
          actualDate: null,
          deliveredOnTime: null,
        },
      },
    ],
    reviews: [],
  },
];

module.exports = customers;

// ============================================================
//  QUICK REFERENCE — fields available per level
//
//  Customer:  customerId, name, email, region, tier, joinedAt,
//             address{city,state,pincode}, orders[], reviews[]
//
//  Order:     orderId, placedAt, status, couponApplied,
//             discountPercent, items[], payment{}, delivery{}
//
//  Item:      productId, productName, category, quantity,
//             unitPrice, itemStatus
//
//  Payment:   method, status, paidAt
//
//  Delivery:  estimatedDate, actualDate, deliveredOnTime
//
//  Review:    productId, rating, helpful, verified
//
//  Regions:   North · South · East · West
//  Tiers:     basic · premium · enterprise
//  Order statuses:    pending · processing · shipped · delivered · cancelled
//  Payment statuses:  paid · pending · failed · refunded
//  Payment methods:   UPI · Card · COD · Wallet
//  Categories:        Electronics · Furniture · Books · Sports · Home
// ============================================================
