// ============================================================
//  VIDYAPATH ACADEMY — Student & Results Dataset
//  Practice Data for JS Interviews
// ============================================================

const students = [
  {
    id: "STU001",
    name: "Aarav Shah",
    age: 17,
    gender: "male",
    email: "aarav.shah@vidyapath.edu",
    phone: "+91-9876501001",
    class: "12A",
    section: "A",
    standard: 12,
    category: "Science",
    city: "Ahmedabad",
    state: "Gujarat",
    feeStatus: "paid",
    admissionYear: 2022,
    scholarshipHolder: true,
    attendance: { total: 220, present: 205, percentage: 93.18 },
    guardian: {
      name: "Ramesh Shah",
      relation: "father",
      contact: "+91-9876501000",
    },
    subjects: [
      {
        code: "PHY12",
        name: "Physics",
        marks: 88,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-10",
      },
      {
        code: "CHE12",
        name: "Chemistry",
        marks: 76,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-12",
      },
      {
        code: "MAT12",
        name: "Mathematics",
        marks: 95,
        maxMarks: 100,
        grade: "A+",
        isPassed: true,
        examDate: "2024-03-14",
      },
      {
        code: "BIO12",
        name: "Biology",
        marks: 82,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-16",
      },
      {
        code: "ENG12",
        name: "English",
        marks: 79,
        maxMarks: 100,
        grade: "B+",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: ["Chess Club", "Science Olympiad"],
    behaviorScore: 9,
    teacherRemarks: "Excellent student, consistent performer",
  },
  {
    id: "STU002",
    name: "Priya Verma",
    age: 16,
    gender: "female",
    email: "priya.verma@vidyapath.edu",
    phone: "+91-9876502002",
    class: "11B",
    section: "B",
    standard: 11,
    category: "Commerce",
    city: "Surat",
    state: "Gujarat",
    feeStatus: "paid",
    admissionYear: 2023,
    scholarshipHolder: false,
    attendance: { total: 210, present: 189, percentage: 90.0 },
    guardian: {
      name: "Sunita Verma",
      relation: "mother",
      contact: "+91-9876502000",
    },
    subjects: [
      {
        code: "ACC11",
        name: "Accountancy",
        marks: 91,
        maxMarks: 100,
        grade: "A+",
        isPassed: true,
        examDate: "2024-03-10",
      },
      {
        code: "ECO11",
        name: "Economics",
        marks: 84,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-12",
      },
      {
        code: "BST11",
        name: "Business Studies",
        marks: 88,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-14",
      },
      {
        code: "MAT11",
        name: "Mathematics",
        marks: 72,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-16",
      },
      {
        code: "ENG11",
        name: "English",
        marks: 80,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: ["Debate Club", "Dance Team"],
    behaviorScore: 8,
    teacherRemarks: "Bright student, good leadership qualities",
  },
  {
    id: "STU003",
    name: "Rohan Patel",
    age: 15,
    gender: "male",
    email: "rohan.patel@vidyapath.edu",
    phone: "+91-9876503003",
    class: "10C",
    section: "C",
    standard: 10,
    category: "General",
    city: "Vadodara",
    state: "Gujarat",
    feeStatus: "pending",
    admissionYear: 2022,
    scholarshipHolder: false,
    attendance: { total: 200, present: 140, percentage: 70.0 },
    guardian: {
      name: "Mahesh Patel",
      relation: "father",
      contact: "+91-9876503000",
    },
    subjects: [
      {
        code: "MAT10",
        name: "Mathematics",
        marks: 34,
        maxMarks: 100,
        grade: "F",
        isPassed: false,
        examDate: "2024-03-10",
      },
      {
        code: "SCI10",
        name: "Science",
        marks: 45,
        maxMarks: 100,
        grade: "D",
        isPassed: true,
        examDate: "2024-03-12",
      },
      {
        code: "SST10",
        name: "Social Studies",
        marks: 55,
        maxMarks: 100,
        grade: "C",
        isPassed: true,
        examDate: "2024-03-14",
      },
      {
        code: "ENG10",
        name: "English",
        marks: 48,
        maxMarks: 100,
        grade: "D",
        isPassed: true,
        examDate: "2024-03-16",
      },
      {
        code: "HIN10",
        name: "Hindi",
        marks: 60,
        maxMarks: 100,
        grade: "C",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: ["Football Team"],
    behaviorScore: 6,
    teacherRemarks: "Needs improvement in academics, active in sports",
  },
  {
    id: "STU004",
    name: "Sneha Joshi",
    age: 17,
    gender: "female",
    email: "sneha.joshi@vidyapath.edu",
    phone: "+91-9876504004",
    class: "12B",
    section: "B",
    standard: 12,
    category: "Science",
    city: "Rajkot",
    state: "Gujarat",
    feeStatus: "paid",
    admissionYear: 2022,
    scholarshipHolder: true,
    attendance: { total: 220, present: 218, percentage: 99.09 },
    guardian: {
      name: "Kavita Joshi",
      relation: "mother",
      contact: "+91-9876504000",
    },
    subjects: [
      {
        code: "PHY12",
        name: "Physics",
        marks: 97,
        maxMarks: 100,
        grade: "A+",
        isPassed: true,
        examDate: "2024-03-10",
      },
      {
        code: "CHE12",
        name: "Chemistry",
        marks: 94,
        maxMarks: 100,
        grade: "A+",
        isPassed: true,
        examDate: "2024-03-12",
      },
      {
        code: "MAT12",
        name: "Mathematics",
        marks: 99,
        maxMarks: 100,
        grade: "A+",
        isPassed: true,
        examDate: "2024-03-14",
      },
      {
        code: "BIO12",
        name: "Biology",
        marks: 96,
        maxMarks: 100,
        grade: "A+",
        isPassed: true,
        examDate: "2024-03-16",
      },
      {
        code: "ENG12",
        name: "English",
        marks: 91,
        maxMarks: 100,
        grade: "A+",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: ["Science Olympiad", "Robotics Club", "Student Council"],
    behaviorScore: 10,
    teacherRemarks: "School topper, exceptional in all areas",
  },
  {
    id: "STU005",
    name: "Karan Mehta",
    age: 16,
    gender: "male",
    email: "karan.mehta@vidyapath.edu",
    phone: "+91-9876505005",
    class: "11A",
    section: "A",
    standard: 11,
    category: "Science",
    city: "Ahmedabad",
    state: "Gujarat",
    feeStatus: "paid",
    admissionYear: 2023,
    scholarshipHolder: false,
    attendance: { total: 210, present: 178, percentage: 84.76 },
    guardian: {
      name: "Dinesh Mehta",
      relation: "father",
      contact: "+91-9876505000",
    },
    subjects: [
      {
        code: "PHY11",
        name: "Physics",
        marks: 62,
        maxMarks: 100,
        grade: "C",
        isPassed: true,
        examDate: "2024-03-10",
      },
      {
        code: "CHE11",
        name: "Chemistry",
        marks: 58,
        maxMarks: 100,
        grade: "C",
        isPassed: true,
        examDate: "2024-03-12",
      },
      {
        code: "MAT11",
        name: "Mathematics",
        marks: 70,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-14",
      },
      {
        code: "BIO11",
        name: "Biology",
        marks: 55,
        maxMarks: 100,
        grade: "C",
        isPassed: true,
        examDate: "2024-03-16",
      },
      {
        code: "ENG11",
        name: "English",
        marks: 65,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: ["Cricket Team"],
    behaviorScore: 7,
    teacherRemarks: "Average performer, can do better",
  },
  {
    id: "STU006",
    name: "Divya Nair",
    age: 15,
    gender: "female",
    email: "divya.nair@vidyapath.edu",
    phone: "+91-9876506006",
    class: "10A",
    section: "A",
    standard: 10,
    category: "General",
    city: "Mumbai",
    state: "Maharashtra",
    feeStatus: "paid",
    admissionYear: 2022,
    scholarshipHolder: true,
    attendance: { total: 200, present: 196, percentage: 98.0 },
    guardian: {
      name: "Latha Nair",
      relation: "mother",
      contact: "+91-9876506000",
    },
    subjects: [
      {
        code: "MAT10",
        name: "Mathematics",
        marks: 93,
        maxMarks: 100,
        grade: "A+",
        isPassed: true,
        examDate: "2024-03-10",
      },
      {
        code: "SCI10",
        name: "Science",
        marks: 89,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-12",
      },
      {
        code: "SST10",
        name: "Social Studies",
        marks: 85,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-14",
      },
      {
        code: "ENG10",
        name: "English",
        marks: 92,
        maxMarks: 100,
        grade: "A+",
        isPassed: true,
        examDate: "2024-03-16",
      },
      {
        code: "HIN10",
        name: "Hindi",
        marks: 78,
        maxMarks: 100,
        grade: "B+",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: ["Dance Team", "Art Club", "Student Council"],
    behaviorScore: 9,
    teacherRemarks: "Consistent, well-rounded student",
  },
  {
    id: "STU007",
    name: "Amit Sharma",
    age: 17,
    gender: "male",
    email: "amit.sharma@vidyapath.edu",
    phone: "+91-9876507007",
    class: "12C",
    section: "C",
    standard: 12,
    category: "Arts",
    city: "Pune",
    state: "Maharashtra",
    feeStatus: "pending",
    admissionYear: 2022,
    scholarshipHolder: false,
    attendance: { total: 220, present: 160, percentage: 72.72 },
    guardian: {
      name: "Vijay Sharma",
      relation: "father",
      contact: "+91-9876507000",
    },
    subjects: [
      {
        code: "HIS12",
        name: "History",
        marks: 55,
        maxMarks: 100,
        grade: "C",
        isPassed: true,
        examDate: "2024-03-10",
      },
      {
        code: "GEO12",
        name: "Geography",
        marks: 49,
        maxMarks: 100,
        grade: "D",
        isPassed: true,
        examDate: "2024-03-12",
      },
      {
        code: "POL12",
        name: "Political Science",
        marks: 38,
        maxMarks: 100,
        grade: "F",
        isPassed: false,
        examDate: "2024-03-14",
      },
      {
        code: "PSY12",
        name: "Psychology",
        marks: 62,
        maxMarks: 100,
        grade: "C",
        isPassed: true,
        examDate: "2024-03-16",
      },
      {
        code: "ENG12",
        name: "English",
        marks: 44,
        maxMarks: 100,
        grade: "D",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: ["Theatre Club"],
    behaviorScore: 5,
    teacherRemarks: "Irregular attendance affecting performance",
  },
  {
    id: "STU008",
    name: "Meera Reddy",
    age: 16,
    gender: "female",
    email: "meera.reddy@vidyapath.edu",
    phone: "+91-9876508008",
    class: "11C",
    section: "C",
    standard: 11,
    category: "Commerce",
    city: "Hyderabad",
    state: "Telangana",
    feeStatus: "paid",
    admissionYear: 2023,
    scholarshipHolder: false,
    attendance: { total: 210, present: 195, percentage: 92.85 },
    guardian: {
      name: "Suresh Reddy",
      relation: "father",
      contact: "+91-9876508000",
    },
    subjects: [
      {
        code: "ACC11",
        name: "Accountancy",
        marks: 78,
        maxMarks: 100,
        grade: "B+",
        isPassed: true,
        examDate: "2024-03-10",
      },
      {
        code: "ECO11",
        name: "Economics",
        marks: 81,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-12",
      },
      {
        code: "BST11",
        name: "Business Studies",
        marks: 75,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-14",
      },
      {
        code: "MAT11",
        name: "Mathematics",
        marks: 68,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-16",
      },
      {
        code: "ENG11",
        name: "English",
        marks: 74,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: ["Commerce Club", "Quiz Team"],
    behaviorScore: 8,
    teacherRemarks: "Good understanding of commerce subjects",
  },
  {
    id: "STU009",
    name: "Vikram Singh",
    age: 15,
    gender: "male",
    email: "vikram.singh@vidyapath.edu",
    phone: "+91-9876509009",
    class: "10B",
    section: "B",
    standard: 10,
    category: "General",
    city: "Jaipur",
    state: "Rajasthan",
    feeStatus: "paid",
    admissionYear: 2022,
    scholarshipHolder: false,
    attendance: { total: 200, present: 155, percentage: 77.5 },
    guardian: {
      name: "Rajendra Singh",
      relation: "father",
      contact: "+91-9876509000",
    },
    subjects: [
      {
        code: "MAT10",
        name: "Mathematics",
        marks: 58,
        maxMarks: 100,
        grade: "C",
        isPassed: true,
        examDate: "2024-03-10",
      },
      {
        code: "SCI10",
        name: "Science",
        marks: 64,
        maxMarks: 100,
        grade: "C",
        isPassed: true,
        examDate: "2024-03-12",
      },
      {
        code: "SST10",
        name: "Social Studies",
        marks: 70,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-14",
      },
      {
        code: "ENG10",
        name: "English",
        marks: 55,
        maxMarks: 100,
        grade: "C",
        isPassed: true,
        examDate: "2024-03-16",
      },
      {
        code: "HIN10",
        name: "Hindi",
        marks: 75,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: ["Football Team", "NCC"],
    behaviorScore: 7,
    teacherRemarks: "Decent student, strong in Hindi and Social Studies",
  },
  {
    id: "STU010",
    name: "Ananya Gupta",
    age: 17,
    gender: "female",
    email: "ananya.gupta@vidyapath.edu",
    phone: "+91-9876510010",
    class: "12A",
    section: "A",
    standard: 12,
    category: "Science",
    city: "Delhi",
    state: "Delhi",
    feeStatus: "paid",
    admissionYear: 2022,
    scholarshipHolder: true,
    attendance: { total: 220, present: 211, percentage: 95.9 },
    guardian: {
      name: "Anil Gupta",
      relation: "father",
      contact: "+91-9876510000",
    },
    subjects: [
      {
        code: "PHY12",
        name: "Physics",
        marks: 91,
        maxMarks: 100,
        grade: "A+",
        isPassed: true,
        examDate: "2024-03-10",
      },
      {
        code: "CHE12",
        name: "Chemistry",
        marks: 87,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-12",
      },
      {
        code: "MAT12",
        name: "Mathematics",
        marks: 94,
        maxMarks: 100,
        grade: "A+",
        isPassed: true,
        examDate: "2024-03-14",
      },
      {
        code: "BIO12",
        name: "Biology",
        marks: 89,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-16",
      },
      {
        code: "ENG12",
        name: "English",
        marks: 85,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: ["Science Olympiad", "Debate Club"],
    behaviorScore: 9,
    teacherRemarks: "Hardworking and focused, great potential",
  },
  {
    id: "STU011",
    name: "Ravi Kumar",
    age: 16,
    gender: "male",
    email: "ravi.kumar@vidyapath.edu",
    phone: "+91-9876511011",
    class: "11A",
    section: "A",
    standard: 11,
    category: "Science",
    city: "Chennai",
    state: "Tamil Nadu",
    feeStatus: "paid",
    admissionYear: 2023,
    scholarshipHolder: false,
    attendance: { total: 210, present: 200, percentage: 95.23 },
    guardian: {
      name: "Murugan Kumar",
      relation: "father",
      contact: "+91-9876511000",
    },
    subjects: [
      {
        code: "PHY11",
        name: "Physics",
        marks: 75,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-10",
      },
      {
        code: "CHE11",
        name: "Chemistry",
        marks: 80,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-12",
      },
      {
        code: "MAT11",
        name: "Mathematics",
        marks: 85,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-14",
      },
      {
        code: "BIO11",
        name: "Biology",
        marks: 78,
        maxMarks: 100,
        grade: "B+",
        isPassed: true,
        examDate: "2024-03-16",
      },
      {
        code: "ENG11",
        name: "English",
        marks: 70,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: ["Chess Club", "Robotics Club"],
    behaviorScore: 8,
    teacherRemarks: "Steady performer, especially strong in Maths",
  },
  {
    id: "STU012",
    name: "Pooja Desai",
    age: 15,
    gender: "female",
    email: "pooja.desai@vidyapath.edu",
    phone: "+91-9876512012",
    class: "10A",
    section: "A",
    standard: 10,
    category: "General",
    city: "Surat",
    state: "Gujarat",
    feeStatus: "paid",
    admissionYear: 2022,
    scholarshipHolder: false,
    attendance: { total: 200, present: 180, percentage: 90.0 },
    guardian: {
      name: "Bhavesh Desai",
      relation: "father",
      contact: "+91-9876512000",
    },
    subjects: [
      {
        code: "MAT10",
        name: "Mathematics",
        marks: 72,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-10",
      },
      {
        code: "SCI10",
        name: "Science",
        marks: 68,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-12",
      },
      {
        code: "SST10",
        name: "Social Studies",
        marks: 74,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-14",
      },
      {
        code: "ENG10",
        name: "English",
        marks: 82,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-16",
      },
      {
        code: "HIN10",
        name: "Hindi",
        marks: 79,
        maxMarks: 100,
        grade: "B+",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: ["Art Club", "Yoga Club"],
    behaviorScore: 8,
    teacherRemarks: "Good all-rounder, excels in languages",
  },
  {
    id: "STU013",
    name: "Harsh Malhotra",
    age: 17,
    gender: "male",
    email: "harsh.malhotra@vidyapath.edu",
    phone: "+91-9876513013",
    class: "12B",
    section: "B",
    standard: 12,
    category: "Commerce",
    city: "Chandigarh",
    state: "Punjab",
    feeStatus: "pending",
    admissionYear: 2022,
    scholarshipHolder: false,
    attendance: { total: 220, present: 155, percentage: 70.45 },
    guardian: {
      name: "Sunil Malhotra",
      relation: "father",
      contact: "+91-9876513000",
    },
    subjects: [
      {
        code: "ACC12",
        name: "Accountancy",
        marks: 44,
        maxMarks: 100,
        grade: "D",
        isPassed: true,
        examDate: "2024-03-10",
      },
      {
        code: "ECO12",
        name: "Economics",
        marks: 38,
        maxMarks: 100,
        grade: "F",
        isPassed: false,
        examDate: "2024-03-12",
      },
      {
        code: "BST12",
        name: "Business Studies",
        marks: 42,
        maxMarks: 100,
        grade: "D",
        isPassed: true,
        examDate: "2024-03-14",
      },
      {
        code: "MAT12",
        name: "Mathematics",
        marks: 29,
        maxMarks: 100,
        grade: "F",
        isPassed: false,
        examDate: "2024-03-16",
      },
      {
        code: "ENG12",
        name: "English",
        marks: 48,
        maxMarks: 100,
        grade: "D",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: ["Gaming Club"],
    behaviorScore: 4,
    teacherRemarks: "Serious intervention needed, poor attendance and results",
  },
  {
    id: "STU014",
    name: "Tanvi Bhatt",
    age: 16,
    gender: "female",
    email: "tanvi.bhatt@vidyapath.edu",
    phone: "+91-9876514014",
    class: "11B",
    section: "B",
    standard: 11,
    category: "Arts",
    city: "Ahmedabad",
    state: "Gujarat",
    feeStatus: "paid",
    admissionYear: 2023,
    scholarshipHolder: false,
    attendance: { total: 210, present: 198, percentage: 94.28 },
    guardian: {
      name: "Nilesh Bhatt",
      relation: "father",
      contact: "+91-9876514000",
    },
    subjects: [
      {
        code: "HIS11",
        name: "History",
        marks: 82,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-10",
      },
      {
        code: "GEO11",
        name: "Geography",
        marks: 78,
        maxMarks: 100,
        grade: "B+",
        isPassed: true,
        examDate: "2024-03-12",
      },
      {
        code: "POL11",
        name: "Political Science",
        marks: 85,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-14",
      },
      {
        code: "PSY11",
        name: "Psychology",
        marks: 90,
        maxMarks: 100,
        grade: "A+",
        isPassed: true,
        examDate: "2024-03-16",
      },
      {
        code: "ENG11",
        name: "English",
        marks: 88,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: ["Debate Club", "Theatre Club", "Student Council"],
    behaviorScore: 9,
    teacherRemarks: "Excellent in humanities, natural speaker",
  },
  {
    id: "STU015",
    name: "Nikhil Rao",
    age: 17,
    gender: "male",
    email: "nikhil.rao@vidyapath.edu",
    phone: "+91-9876515015",
    class: "12C",
    section: "C",
    standard: 12,
    category: "Science",
    city: "Bangalore",
    state: "Karnataka",
    feeStatus: "paid",
    admissionYear: 2022,
    scholarshipHolder: true,
    attendance: { total: 220, present: 202, percentage: 91.81 },
    guardian: {
      name: "Prasad Rao",
      relation: "father",
      contact: "+91-9876515000",
    },
    subjects: [
      {
        code: "PHY12",
        name: "Physics",
        marks: 83,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-10",
      },
      {
        code: "CHE12",
        name: "Chemistry",
        marks: 79,
        maxMarks: 100,
        grade: "B+",
        isPassed: true,
        examDate: "2024-03-12",
      },
      {
        code: "MAT12",
        name: "Mathematics",
        marks: 90,
        maxMarks: 100,
        grade: "A+",
        isPassed: true,
        examDate: "2024-03-14",
      },
      {
        code: "BIO12",
        name: "Biology",
        marks: 74,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-16",
      },
      {
        code: "ENG12",
        name: "English",
        marks: 77,
        maxMarks: 100,
        grade: "B+",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: ["Robotics Club", "Science Olympiad"],
    behaviorScore: 8,
    teacherRemarks: "Strong analytical skills, good in STEM",
  },
  {
    id: "STU016",
    name: "Sanya Kapoor",
    age: 16,
    gender: "female",
    email: "sanya.kapoor@vidyapath.edu",
    phone: "+91-9876516016",
    class: "11C",
    section: "C",
    standard: 11,
    category: "Commerce",
    city: "Mumbai",
    state: "Maharashtra",
    feeStatus: "paid",
    admissionYear: 2023,
    scholarshipHolder: true,
    attendance: { total: 210, present: 207, percentage: 98.57 },
    guardian: {
      name: "Rajan Kapoor",
      relation: "father",
      contact: "+91-9876516000",
    },
    subjects: [
      {
        code: "ACC11",
        name: "Accountancy",
        marks: 95,
        maxMarks: 100,
        grade: "A+",
        isPassed: true,
        examDate: "2024-03-10",
      },
      {
        code: "ECO11",
        name: "Economics",
        marks: 90,
        maxMarks: 100,
        grade: "A+",
        isPassed: true,
        examDate: "2024-03-12",
      },
      {
        code: "BST11",
        name: "Business Studies",
        marks: 92,
        maxMarks: 100,
        grade: "A+",
        isPassed: true,
        examDate: "2024-03-14",
      },
      {
        code: "MAT11",
        name: "Mathematics",
        marks: 88,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-16",
      },
      {
        code: "ENG11",
        name: "English",
        marks: 91,
        maxMarks: 100,
        grade: "A+",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: ["Commerce Club", "Student Council", "Quiz Team"],
    behaviorScore: 10,
    teacherRemarks: "Class topper in Commerce, future CA material",
  },
  {
    id: "STU017",
    name: "Dev Arora",
    age: 15,
    gender: "male",
    email: "dev.arora@vidyapath.edu",
    phone: "+91-9876517017",
    class: "10B",
    section: "B",
    standard: 10,
    category: "General",
    city: "Noida",
    state: "UP",
    feeStatus: "pending",
    admissionYear: 2022,
    scholarshipHolder: false,
    attendance: { total: 200, present: 148, percentage: 74.0 },
    guardian: {
      name: "Sanjeev Arora",
      relation: "father",
      contact: "+91-9876517000",
    },
    subjects: [
      {
        code: "MAT10",
        name: "Mathematics",
        marks: 40,
        maxMarks: 100,
        grade: "D",
        isPassed: true,
        examDate: "2024-03-10",
      },
      {
        code: "SCI10",
        name: "Science",
        marks: 36,
        maxMarks: 100,
        grade: "F",
        isPassed: false,
        examDate: "2024-03-12",
      },
      {
        code: "SST10",
        name: "Social Studies",
        marks: 52,
        maxMarks: 100,
        grade: "C",
        isPassed: true,
        examDate: "2024-03-14",
      },
      {
        code: "ENG10",
        name: "English",
        marks: 44,
        maxMarks: 100,
        grade: "D",
        isPassed: true,
        examDate: "2024-03-16",
      },
      {
        code: "HIN10",
        name: "Hindi",
        marks: 58,
        maxMarks: 100,
        grade: "C",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: [],
    behaviorScore: 5,
    teacherRemarks: "Low attendance leading to poor academic performance",
  },
  {
    id: "STU018",
    name: "Kavya Iyer",
    age: 17,
    gender: "female",
    email: "kavya.iyer@vidyapath.edu",
    phone: "+91-9876518018",
    class: "12A",
    section: "A",
    standard: 12,
    category: "Arts",
    city: "Chennai",
    state: "Tamil Nadu",
    feeStatus: "paid",
    admissionYear: 2022,
    scholarshipHolder: false,
    attendance: { total: 220, present: 210, percentage: 95.45 },
    guardian: {
      name: "Venkat Iyer",
      relation: "father",
      contact: "+91-9876518000",
    },
    subjects: [
      {
        code: "HIS12",
        name: "History",
        marks: 88,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-10",
      },
      {
        code: "GEO12",
        name: "Geography",
        marks: 84,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-12",
      },
      {
        code: "POL12",
        name: "Political Science",
        marks: 91,
        maxMarks: 100,
        grade: "A+",
        isPassed: true,
        examDate: "2024-03-14",
      },
      {
        code: "PSY12",
        name: "Psychology",
        marks: 87,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-16",
      },
      {
        code: "ENG12",
        name: "English",
        marks: 93,
        maxMarks: 100,
        grade: "A+",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: ["Debate Club", "Literary Club"],
    behaviorScore: 9,
    teacherRemarks: "Outstanding in arts and humanities stream",
  },
  {
    id: "STU019",
    name: "Gaurav Tiwari",
    age: 16,
    gender: "male",
    email: "gaurav.tiwari@vidyapath.edu",
    phone: "+91-9876519019",
    class: "11B",
    section: "B",
    standard: 11,
    category: "Science",
    city: "Lucknow",
    state: "UP",
    feeStatus: "paid",
    admissionYear: 2023,
    scholarshipHolder: false,
    attendance: { total: 210, present: 168, percentage: 80.0 },
    guardian: {
      name: "Ashok Tiwari",
      relation: "father",
      contact: "+91-9876519000",
    },
    subjects: [
      {
        code: "PHY11",
        name: "Physics",
        marks: 68,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-10",
      },
      {
        code: "CHE11",
        name: "Chemistry",
        marks: 72,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-12",
      },
      {
        code: "MAT11",
        name: "Mathematics",
        marks: 78,
        maxMarks: 100,
        grade: "B+",
        isPassed: true,
        examDate: "2024-03-14",
      },
      {
        code: "BIO11",
        name: "Biology",
        marks: 65,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-16",
      },
      {
        code: "ENG11",
        name: "English",
        marks: 60,
        maxMarks: 100,
        grade: "C",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: ["Cricket Team", "NCC"],
    behaviorScore: 7,
    teacherRemarks: "Good in sciences, needs to focus more on English",
  },
  {
    id: "STU020",
    name: "Anita Pillai",
    age: 15,
    gender: "female",
    email: "anita.pillai@vidyapath.edu",
    phone: "+91-9876520020",
    class: "10C",
    section: "C",
    standard: 10,
    category: "General",
    city: "Kochi",
    state: "Kerala",
    feeStatus: "paid",
    admissionYear: 2022,
    scholarshipHolder: true,
    attendance: { total: 200, present: 194, percentage: 97.0 },
    guardian: {
      name: "Gopalan Pillai",
      relation: "father",
      contact: "+91-9876520000",
    },
    subjects: [
      {
        code: "MAT10",
        name: "Mathematics",
        marks: 87,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-10",
      },
      {
        code: "SCI10",
        name: "Science",
        marks: 91,
        maxMarks: 100,
        grade: "A+",
        isPassed: true,
        examDate: "2024-03-12",
      },
      {
        code: "SST10",
        name: "Social Studies",
        marks: 83,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-14",
      },
      {
        code: "ENG10",
        name: "English",
        marks: 88,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-16",
      },
      {
        code: "HIN10",
        name: "Hindi",
        marks: 70,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: ["Science Olympiad", "Yoga Club"],
    behaviorScore: 9,
    teacherRemarks: "Exceptional focus and discipline",
  },
  {
    id: "STU021",
    name: "Saurabh Jain",
    age: 17,
    gender: "male",
    email: "saurabh.jain@vidyapath.edu",
    phone: "+91-9876521021",
    class: "12B",
    section: "B",
    standard: 12,
    category: "Commerce",
    city: "Indore",
    state: "Madhya Pradesh",
    feeStatus: "paid",
    admissionYear: 2022,
    scholarshipHolder: false,
    attendance: { total: 220, present: 190, percentage: 86.36 },
    guardian: {
      name: "Prakash Jain",
      relation: "father",
      contact: "+91-9876521000",
    },
    subjects: [
      {
        code: "ACC12",
        name: "Accountancy",
        marks: 82,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-10",
      },
      {
        code: "ECO12",
        name: "Economics",
        marks: 76,
        maxMarks: 100,
        grade: "B+",
        isPassed: true,
        examDate: "2024-03-12",
      },
      {
        code: "BST12",
        name: "Business Studies",
        marks: 80,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-14",
      },
      {
        code: "MAT12",
        name: "Mathematics",
        marks: 71,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-16",
      },
      {
        code: "ENG12",
        name: "English",
        marks: 68,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: ["Commerce Club", "Cricket Team"],
    behaviorScore: 7,
    teacherRemarks: "Solid commerce student, good analytical skills",
  },
  {
    id: "STU022",
    name: "Leena Krishnan",
    age: 16,
    gender: "female",
    email: "leena.krishnan@vidyapath.edu",
    phone: "+91-9876522022",
    class: "11A",
    section: "A",
    standard: 11,
    category: "Science",
    city: "Coimbatore",
    state: "Tamil Nadu",
    feeStatus: "paid",
    admissionYear: 2023,
    scholarshipHolder: false,
    attendance: { total: 210, present: 185, percentage: 88.09 },
    guardian: {
      name: "Krishnamurthy L",
      relation: "father",
      contact: "+91-9876522000",
    },
    subjects: [
      {
        code: "PHY11",
        name: "Physics",
        marks: 70,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-10",
      },
      {
        code: "CHE11",
        name: "Chemistry",
        marks: 74,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-12",
      },
      {
        code: "MAT11",
        name: "Mathematics",
        marks: 80,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-14",
      },
      {
        code: "BIO11",
        name: "Biology",
        marks: 83,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-16",
      },
      {
        code: "ENG11",
        name: "English",
        marks: 76,
        maxMarks: 100,
        grade: "B+",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: ["Biology Club", "Dance Team"],
    behaviorScore: 8,
    teacherRemarks: "Strong in Biology, consistent effort",
  },
  {
    id: "STU023",
    name: "Rahul Saxena",
    age: 15,
    gender: "male",
    email: "rahul.saxena@vidyapath.edu",
    phone: "+91-9876523023",
    class: "10C",
    section: "C",
    standard: 10,
    category: "General",
    city: "Bhopal",
    state: "Madhya Pradesh",
    feeStatus: "pending",
    admissionYear: 2022,
    scholarshipHolder: false,
    attendance: { total: 200, present: 130, percentage: 65.0 },
    guardian: {
      name: "Deepak Saxena",
      relation: "father",
      contact: "+91-9876523000",
    },
    subjects: [
      {
        code: "MAT10",
        name: "Mathematics",
        marks: 28,
        maxMarks: 100,
        grade: "F",
        isPassed: false,
        examDate: "2024-03-10",
      },
      {
        code: "SCI10",
        name: "Science",
        marks: 32,
        maxMarks: 100,
        grade: "F",
        isPassed: false,
        examDate: "2024-03-12",
      },
      {
        code: "SST10",
        name: "Social Studies",
        marks: 45,
        maxMarks: 100,
        grade: "D",
        isPassed: true,
        examDate: "2024-03-14",
      },
      {
        code: "ENG10",
        name: "English",
        marks: 38,
        maxMarks: 100,
        grade: "F",
        isPassed: false,
        examDate: "2024-03-16",
      },
      {
        code: "HIN10",
        name: "Hindi",
        marks: 50,
        maxMarks: 100,
        grade: "C",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: [],
    behaviorScore: 3,
    teacherRemarks: "Critical case — requires immediate academic support",
  },
  {
    id: "STU024",
    name: "Pooja Menon",
    age: 17,
    gender: "female",
    email: "pooja.menon@vidyapath.edu",
    phone: "+91-9876524024",
    class: "12C",
    section: "C",
    standard: 12,
    category: "Arts",
    city: "Thrissur",
    state: "Kerala",
    feeStatus: "paid",
    admissionYear: 2022,
    scholarshipHolder: true,
    attendance: { total: 220, present: 215, percentage: 97.72 },
    guardian: {
      name: "Anil Menon",
      relation: "father",
      contact: "+91-9876524000",
    },
    subjects: [
      {
        code: "HIS12",
        name: "History",
        marks: 90,
        maxMarks: 100,
        grade: "A+",
        isPassed: true,
        examDate: "2024-03-10",
      },
      {
        code: "GEO12",
        name: "Geography",
        marks: 87,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-12",
      },
      {
        code: "POL12",
        name: "Political Science",
        marks: 93,
        maxMarks: 100,
        grade: "A+",
        isPassed: true,
        examDate: "2024-03-14",
      },
      {
        code: "PSY12",
        name: "Psychology",
        marks: 89,
        maxMarks: 100,
        grade: "A",
        isPassed: true,
        examDate: "2024-03-16",
      },
      {
        code: "ENG12",
        name: "English",
        marks: 95,
        maxMarks: 100,
        grade: "A+",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: ["Literary Club", "Debate Club", "Theatre Club"],
    behaviorScore: 10,
    teacherRemarks: "Brilliant student, arts topper, exemplary behavior",
  },
  {
    id: "STU025",
    name: "Arjun Nambiar",
    age: 16,
    gender: "male",
    email: "arjun.nambiar@vidyapath.edu",
    phone: "+91-9876525025",
    class: "11C",
    section: "C",
    standard: 11,
    category: "Commerce",
    city: "Kozhikode",
    state: "Kerala",
    feeStatus: "paid",
    admissionYear: 2023,
    scholarshipHolder: false,
    attendance: { total: 210, present: 172, percentage: 81.9 },
    guardian: {
      name: "Rajan Nambiar",
      relation: "father",
      contact: "+91-9876525000",
    },
    subjects: [
      {
        code: "ACC11",
        name: "Accountancy",
        marks: 66,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-10",
      },
      {
        code: "ECO11",
        name: "Economics",
        marks: 70,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-12",
      },
      {
        code: "BST11",
        name: "Business Studies",
        marks: 63,
        maxMarks: 100,
        grade: "C",
        isPassed: true,
        examDate: "2024-03-14",
      },
      {
        code: "MAT11",
        name: "Mathematics",
        marks: 58,
        maxMarks: 100,
        grade: "C",
        isPassed: true,
        examDate: "2024-03-16",
      },
      {
        code: "ENG11",
        name: "English",
        marks: 72,
        maxMarks: 100,
        grade: "B",
        isPassed: true,
        examDate: "2024-03-18",
      },
    ],
    extracurricular: ["Football Team"],
    behaviorScore: 7,
    teacherRemarks: "Average, needs to push harder in Maths and BST",
  },
];
module.exports = students;
