/**
 * ============================================================
 * HOSPITAL DATASET — hospital-dataset.js
 * ============================================================
 * 40 patients · 12 doctors · 6 departments · 3 hospitals
 * Use this for all 50 questions in Hospital-50-Questions.md
 * ============================================================
 */

export const hospitalData = [
  // ─────────────────────────────────────────────
  // HOSPITAL 1 — City General Hospital (Mumbai)
  // ─────────────────────────────────────────────
  {
    patientId: "PT001",
    name: "Arjun Mehta",
    age: 45,
    gender: "Male",
    bloodGroup: "A+",
    city: "Mumbai",
    hospital: "City General Hospital",
    insuranceProvider: "StarHealth",
    insuranceCovered: true,
    admissions: [
      {
        admissionId: "ADM001",
        admittedAt: "2024-01-10",
        dischargedAt: "2024-01-15",
        department: "Cardiology",
        doctorId: "DR001",
        diagnosis: "Hypertension",
        severity: "moderate",
        totalBill: 32000,
        insurancePaid: 28000,
        patientPaid: 4000,
        tests: [
          { testName: "ECG", cost: 1500, result: "abnormal" },
          { testName: "Blood Pressure", cost: 300, result: "high" },
          { testName: "Cholesterol", cost: 800, result: "high" },
        ],
        medications: [
          { name: "Amlodipine", dosage: "5mg", days: 30 },
          { name: "Aspirin", dosage: "75mg", days: 30 },
        ],
        readmitted: false,
      },
      {
        admissionId: "ADM002",
        admittedAt: "2024-06-20",
        dischargedAt: "2024-06-22",
        department: "Cardiology",
        doctorId: "DR001",
        diagnosis: "Chest Pain",
        severity: "high",
        totalBill: 18000,
        insurancePaid: 15000,
        patientPaid: 3000,
        tests: [
          { testName: "ECG", cost: 1500, result: "abnormal" },
          { testName: "Troponin", cost: 2200, result: "elevated" },
        ],
        medications: [{ name: "Nitroglycerin", dosage: "0.5mg", days: 7 }],
        readmitted: true, // readmission within 6 months
      },
    ],
    reviews: [
      {
        doctorId: "DR001",
        rating: 4,
        comment: "Good care",
        date: "2024-01-16",
      },
    ],
  },
  {
    patientId: "PT002",
    name: "Priya Sharma",
    age: 32,
    gender: "Female",
    bloodGroup: "B+",
    city: "Mumbai",
    hospital: "City General Hospital",
    insuranceProvider: "HDFCErgo",
    insuranceCovered: true,
    admissions: [
      {
        admissionId: "ADM003",
        admittedAt: "2024-02-05",
        dischargedAt: "2024-02-08",
        department: "Gynecology",
        doctorId: "DR004",
        diagnosis: "PCOS",
        severity: "low",
        totalBill: 12000,
        insurancePaid: 10000,
        patientPaid: 2000,
        tests: [
          { testName: "Ultrasound", cost: 2500, result: "cysts detected" },
          { testName: "Hormone Panel", cost: 3200, result: "imbalanced" },
        ],
        medications: [{ name: "Metformin", dosage: "500mg", days: 90 }],
        readmitted: false,
      },
    ],
    reviews: [
      {
        doctorId: "DR004",
        rating: 5,
        comment: "Excellent doctor",
        date: "2024-02-09",
      },
    ],
  },
  {
    patientId: "PT003",
    name: "Ravi Kumar",
    age: 67,
    gender: "Male",
    bloodGroup: "O+",
    city: "Mumbai",
    hospital: "City General Hospital",
    insuranceProvider: "StarHealth",
    insuranceCovered: true,
    admissions: [
      {
        admissionId: "ADM004",
        admittedAt: "2024-03-12",
        dischargedAt: "2024-03-20",
        department: "Orthopedics",
        doctorId: "DR006",
        diagnosis: "Hip Fracture",
        severity: "high",
        totalBill: 85000,
        insurancePaid: 75000,
        patientPaid: 10000,
        tests: [
          { testName: "X-Ray", cost: 1200, result: "fracture confirmed" },
          { testName: "MRI", cost: 8500, result: "ligament damage" },
        ],
        medications: [
          { name: "Calcium", dosage: "500mg", days: 60 },
          { name: "Vitamin D", dosage: "1000IU", days: 60 },
          { name: "Tramadol", dosage: "50mg", days: 14 },
        ],
        readmitted: false,
      },
    ],
    reviews: [],
  },
  {
    patientId: "PT004",
    name: "Sneha Patil",
    age: 28,
    gender: "Female",
    bloodGroup: "AB+",
    city: "Mumbai",
    hospital: "City General Hospital",
    insuranceProvider: null,
    insuranceCovered: false,
    admissions: [
      {
        admissionId: "ADM005",
        admittedAt: "2024-04-01",
        dischargedAt: "2024-04-02",
        department: "Emergency",
        doctorId: "DR009",
        diagnosis: "Appendicitis",
        severity: "critical",
        totalBill: 45000,
        insurancePaid: 0,
        patientPaid: 45000,
        tests: [
          { testName: "CT Scan", cost: 6500, result: "inflamed appendix" },
          { testName: "Blood CBC", cost: 600, result: "high WBC" },
        ],
        medications: [
          { name: "Ceftriaxone", dosage: "1g", days: 5 },
          { name: "Metronidazole", dosage: "500mg", days: 5 },
        ],
        readmitted: false,
      },
    ],
    reviews: [
      {
        doctorId: "DR009",
        rating: 3,
        comment: "Long waiting time",
        date: "2024-04-03",
      },
    ],
  },
  {
    patientId: "PT005",
    name: "Vikram Singh",
    age: 52,
    gender: "Male",
    bloodGroup: "A-",
    city: "Mumbai",
    hospital: "City General Hospital",
    insuranceProvider: "ICICILombard",
    insuranceCovered: true,
    admissions: [
      {
        admissionId: "ADM006",
        admittedAt: "2024-05-15",
        dischargedAt: "2024-05-19",
        department: "Neurology",
        doctorId: "DR007",
        diagnosis: "Migraine",
        severity: "moderate",
        totalBill: 22000,
        insurancePaid: 18000,
        patientPaid: 4000,
        tests: [
          { testName: "MRI Brain", cost: 8500, result: "normal" },
          { testName: "EEG", cost: 3500, result: "normal" },
        ],
        medications: [
          { name: "Sumatriptan", dosage: "50mg", days: 10 },
          { name: "Propranolol", dosage: "40mg", days: 30 },
        ],
        readmitted: false,
      },
    ],
    reviews: [
      {
        doctorId: "DR007",
        rating: 4,
        comment: "Very knowledgeable",
        date: "2024-05-20",
      },
    ],
  },
  {
    patientId: "PT006",
    name: "Anita Joshi",
    age: 41,
    gender: "Female",
    bloodGroup: "B-",
    city: "Mumbai",
    hospital: "City General Hospital",
    insuranceProvider: "StarHealth",
    insuranceCovered: true,
    admissions: [
      {
        admissionId: "ADM007",
        admittedAt: "2024-07-08",
        dischargedAt: "2024-07-12",
        department: "Gastroenterology",
        doctorId: "DR010",
        diagnosis: "Gastritis",
        severity: "moderate",
        totalBill: 19500,
        insurancePaid: 16000,
        patientPaid: 3500,
        tests: [
          { testName: "Endoscopy", cost: 5500, result: "ulcer detected" },
          { testName: "H. Pylori Test", cost: 1200, result: "positive" },
        ],
        medications: [
          { name: "Pantoprazole", dosage: "40mg", days: 30 },
          { name: "Amoxicillin", dosage: "1g", days: 14 },
        ],
        readmitted: false,
      },
    ],
    reviews: [],
  },
  {
    patientId: "PT007",
    name: "Deepak Nair",
    age: 58,
    gender: "Male",
    bloodGroup: "O-",
    city: "Mumbai",
    hospital: "City General Hospital",
    insuranceProvider: "HDFCErgo",
    insuranceCovered: true,
    admissions: [
      {
        admissionId: "ADM008",
        admittedAt: "2024-08-03",
        dischargedAt: "2024-08-10",
        department: "Cardiology",
        doctorId: "DR001",
        diagnosis: "Heart Failure",
        severity: "critical",
        totalBill: 120000,
        insurancePaid: 100000,
        patientPaid: 20000,
        tests: [
          { testName: "Echocardiogram", cost: 5500, result: "EF 35%" },
          { testName: "BNP Test", cost: 2800, result: "elevated" },
          { testName: "Chest X-Ray", cost: 900, result: "cardiomegaly" },
        ],
        medications: [
          { name: "Furosemide", dosage: "40mg", days: 30 },
          { name: "Carvedilol", dosage: "6.25mg", days: 90 },
          { name: "Lisinopril", dosage: "5mg", days: 90 },
        ],
        readmitted: false,
      },
    ],
    reviews: [
      {
        doctorId: "DR001",
        rating: 5,
        comment: "Saved my life",
        date: "2024-08-11",
      },
    ],
  },
  {
    patientId: "PT008",
    name: "Kavitha Reddy",
    age: 35,
    gender: "Female",
    bloodGroup: "A+",
    city: "Mumbai",
    hospital: "City General Hospital",
    insuranceProvider: null,
    insuranceCovered: false,
    admissions: [
      {
        admissionId: "ADM009",
        admittedAt: "2024-09-14",
        dischargedAt: "2024-09-16",
        department: "Dermatology",
        doctorId: "DR011",
        diagnosis: "Psoriasis",
        severity: "low",
        totalBill: 8500,
        insurancePaid: 0,
        patientPaid: 8500,
        tests: [
          { testName: "Skin Biopsy", cost: 3200, result: "psoriatic plaques" },
        ],
        medications: [
          { name: "Betamethasone", dosage: "0.1%", days: 30 },
          { name: "Vitamin D Cream", dosage: "topical", days: 30 },
        ],
        readmitted: false,
      },
    ],
    reviews: [
      {
        doctorId: "DR011",
        rating: 4,
        comment: "Clear diagnosis",
        date: "2024-09-17",
      },
    ],
  },
  // ─────────────────────────────────────────────
  // HOSPITAL 2 — Apollo Medical Centre (Delhi)
  // ─────────────────────────────────────────────
  {
    patientId: "PT009",
    name: "Rajesh Gupta",
    age: 60,
    gender: "Male",
    bloodGroup: "B+",
    city: "Delhi",
    hospital: "Apollo Medical Centre",
    insuranceProvider: "ICICILombard",
    insuranceCovered: true,
    admissions: [
      {
        admissionId: "ADM010",
        admittedAt: "2024-01-22",
        dischargedAt: "2024-01-28",
        department: "Oncology",
        doctorId: "DR002",
        diagnosis: "Lung Cancer - Stage 2",
        severity: "critical",
        totalBill: 180000,
        insurancePaid: 150000,
        patientPaid: 30000,
        tests: [
          { testName: "CT Chest", cost: 7500, result: "mass detected" },
          { testName: "PET Scan", cost: 22000, result: "localized" },
          { testName: "Biopsy", cost: 12000, result: "malignant" },
        ],
        medications: [
          { name: "Carboplatin", dosage: "400mg", days: 21 },
          { name: "Paclitaxel", dosage: "175mg", days: 21 },
        ],
        readmitted: false,
      },
      {
        admissionId: "ADM011",
        admittedAt: "2024-04-15",
        dischargedAt: "2024-04-20",
        department: "Oncology",
        doctorId: "DR002",
        diagnosis: "Chemotherapy Cycle 2",
        severity: "high",
        totalBill: 95000,
        insurancePaid: 80000,
        patientPaid: 15000,
        tests: [{ testName: "Blood CBC", cost: 600, result: "low WBC" }],
        medications: [
          { name: "Carboplatin", dosage: "400mg", days: 21 },
          { name: "G-CSF", dosage: "300mcg", days: 7 },
        ],
        readmitted: true,
      },
    ],
    reviews: [
      {
        doctorId: "DR002",
        rating: 5,
        comment: "Best oncologist in Delhi",
        date: "2024-05-01",
      },
    ],
  },
  {
    patientId: "PT010",
    name: "Sunita Agarwal",
    age: 48,
    gender: "Female",
    bloodGroup: "O+",
    city: "Delhi",
    hospital: "Apollo Medical Centre",
    insuranceProvider: "StarHealth",
    insuranceCovered: true,
    admissions: [
      {
        admissionId: "ADM012",
        admittedAt: "2024-02-14",
        dischargedAt: "2024-02-17",
        department: "Endocrinology",
        doctorId: "DR005",
        diagnosis: "Type 2 Diabetes",
        severity: "moderate",
        totalBill: 16000,
        insurancePaid: 13000,
        patientPaid: 3000,
        tests: [
          { testName: "HbA1c", cost: 900, result: "8.2%" },
          { testName: "Fasting Glucose", cost: 400, result: "186 mg/dL" },
          { testName: "Kidney Function", cost: 1400, result: "normal" },
        ],
        medications: [
          { name: "Metformin", dosage: "1000mg", days: 90 },
          { name: "Glimepiride", dosage: "2mg", days: 90 },
        ],
        readmitted: false,
      },
    ],
    reviews: [
      {
        doctorId: "DR005",
        rating: 4,
        comment: "Very thorough",
        date: "2024-02-18",
      },
    ],
  },
  {
    patientId: "PT011",
    name: "Manish Tiwari",
    age: 39,
    gender: "Male",
    bloodGroup: "A+",
    city: "Delhi",
    hospital: "Apollo Medical Centre",
    insuranceProvider: "HDFCErgo",
    insuranceCovered: true,
    admissions: [
      {
        admissionId: "ADM013",
        admittedAt: "2024-03-05",
        dischargedAt: "2024-03-07",
        department: "Pulmonology",
        doctorId: "DR008",
        diagnosis: "Asthma",
        severity: "moderate",
        totalBill: 14500,
        insurancePaid: 12000,
        patientPaid: 2500,
        tests: [
          { testName: "Spirometry", cost: 2200, result: "FEV1 reduced" },
          {
            testName: "Allergy Panel",
            cost: 4500,
            result: "dust mite allergy",
          },
        ],
        medications: [
          { name: "Salbutamol", dosage: "100mcg", days: 30 },
          { name: "Fluticasone", dosage: "250mcg", days: 30 },
        ],
        readmitted: false,
      },
    ],
    reviews: [],
  },
  {
    patientId: "PT012",
    name: "Pooja Verma",
    age: 25,
    gender: "Female",
    bloodGroup: "B+",
    city: "Delhi",
    hospital: "Apollo Medical Centre",
    insuranceProvider: null,
    insuranceCovered: false,
    admissions: [
      {
        admissionId: "ADM014",
        admittedAt: "2024-05-20",
        dischargedAt: "2024-05-20",
        department: "Emergency",
        doctorId: "DR009",
        diagnosis: "Fracture - Wrist",
        severity: "moderate",
        totalBill: 12000,
        insurancePaid: 0,
        patientPaid: 12000,
        tests: [
          { testName: "X-Ray", cost: 1200, result: "fracture confirmed" },
        ],
        medications: [
          { name: "Ibuprofen", dosage: "400mg", days: 7 },
          { name: "Calcium", dosage: "500mg", days: 30 },
        ],
        readmitted: false,
      },
    ],
    reviews: [],
  },
  {
    patientId: "PT013",
    name: "Suresh Bansal",
    age: 71,
    gender: "Male",
    bloodGroup: "AB-",
    city: "Delhi",
    hospital: "Apollo Medical Centre",
    insuranceProvider: "ICICILombard",
    insuranceCovered: true,
    admissions: [
      {
        admissionId: "ADM015",
        admittedAt: "2024-06-10",
        dischargedAt: "2024-06-18",
        department: "Urology",
        doctorId: "DR012",
        diagnosis: "Prostate Enlargement",
        severity: "moderate",
        totalBill: 55000,
        insurancePaid: 45000,
        patientPaid: 10000,
        tests: [
          { testName: "PSA Test", cost: 1500, result: "elevated" },
          { testName: "Ultrasound Prostate", cost: 2500, result: "enlarged" },
          { testName: "Urodynamics", cost: 4500, result: "reduced flow" },
        ],
        medications: [
          { name: "Tamsulosin", dosage: "0.4mg", days: 90 },
          { name: "Finasteride", dosage: "5mg", days: 90 },
        ],
        readmitted: false,
      },
    ],
    reviews: [
      {
        doctorId: "DR012",
        rating: 4,
        comment: "Professional and calm",
        date: "2024-06-19",
      },
    ],
  },
  {
    patientId: "PT014",
    name: "Nandini Kapoor",
    age: 29,
    gender: "Female",
    bloodGroup: "O+",
    city: "Delhi",
    hospital: "Apollo Medical Centre",
    insuranceProvider: "StarHealth",
    insuranceCovered: true,
    admissions: [
      {
        admissionId: "ADM016",
        admittedAt: "2024-07-25",
        dischargedAt: "2024-07-26",
        department: "Ophthalmology",
        doctorId: "DR003",
        diagnosis: "LASIK Surgery",
        severity: "low",
        totalBill: 48000,
        insurancePaid: 0, // elective procedure, not covered
        patientPaid: 48000,
        tests: [
          { testName: "Corneal Mapping", cost: 3500, result: "suitable" },
          { testName: "Eye Pressure", cost: 800, result: "normal" },
        ],
        medications: [
          { name: "Moxifloxacin Eye Drops", dosage: "0.5%", days: 7 },
          { name: "Prednisolone Eye Drops", dosage: "1%", days: 14 },
        ],
        readmitted: false,
      },
    ],
    reviews: [
      {
        doctorId: "DR003",
        rating: 5,
        comment: "Amazing results!",
        date: "2024-07-27",
      },
    ],
  },
  {
    patientId: "PT015",
    name: "Aakash Mehrotra",
    age: 44,
    gender: "Male",
    bloodGroup: "A+",
    city: "Delhi",
    hospital: "Apollo Medical Centre",
    insuranceProvider: "HDFCErgo",
    insuranceCovered: true,
    admissions: [
      {
        admissionId: "ADM017",
        admittedAt: "2024-08-18",
        dischargedAt: "2024-08-22",
        department: "Cardiology",
        doctorId: "DR001",
        diagnosis: "Arrhythmia",
        severity: "high",
        totalBill: 42000,
        insurancePaid: 36000,
        patientPaid: 6000,
        tests: [
          { testName: "Holter Monitor", cost: 4500, result: "AF detected" },
          { testName: "ECG", cost: 1500, result: "irregular rhythm" },
          { testName: "Blood Thyroid", cost: 1200, result: "normal" },
        ],
        medications: [
          { name: "Flecainide", dosage: "100mg", days: 30 },
          { name: "Apixaban", dosage: "5mg", days: 90 },
        ],
        readmitted: false,
      },
    ],
    reviews: [],
  },
  // ─────────────────────────────────────────────
  // HOSPITAL 3 — Sunrise Health Institute (Bangalore)
  // ─────────────────────────────────────────────
  {
    patientId: "PT016",
    name: "Kaveri Rao",
    age: 38,
    gender: "Female",
    bloodGroup: "B+",
    city: "Bangalore",
    hospital: "Sunrise Health Institute",
    insuranceProvider: "StarHealth",
    insuranceCovered: true,
    admissions: [
      {
        admissionId: "ADM018",
        admittedAt: "2024-01-30",
        dischargedAt: "2024-02-03",
        department: "Gynecology",
        doctorId: "DR004",
        diagnosis: "Endometriosis",
        severity: "moderate",
        totalBill: 38000,
        insurancePaid: 30000,
        patientPaid: 8000,
        tests: [
          {
            testName: "Laparoscopy",
            cost: 18000,
            result: "endometriosis confirmed",
          },
          { testName: "CA-125", cost: 2200, result: "elevated" },
        ],
        medications: [
          { name: "Leuprolide", dosage: "3.75mg", days: 28 },
          { name: "Norethisterone", dosage: "5mg", days: 30 },
        ],
        readmitted: false,
      },
    ],
    reviews: [
      {
        doctorId: "DR004",
        rating: 5,
        comment: "Very compassionate",
        date: "2024-02-04",
      },
    ],
  },
  {
    patientId: "PT017",
    name: "Harish Gowda",
    age: 55,
    gender: "Male",
    bloodGroup: "O+",
    city: "Bangalore",
    hospital: "Sunrise Health Institute",
    insuranceProvider: "ICICILombard",
    insuranceCovered: true,
    admissions: [
      {
        admissionId: "ADM019",
        admittedAt: "2024-03-18",
        dischargedAt: "2024-03-25",
        department: "Orthopedics",
        doctorId: "DR006",
        diagnosis: "Knee Replacement",
        severity: "high",
        totalBill: 145000,
        insurancePaid: 120000,
        patientPaid: 25000,
        tests: [
          { testName: "X-Ray Knee", cost: 1200, result: "severe arthritis" },
          { testName: "MRI Knee", cost: 8500, result: "cartilage damage" },
          { testName: "Blood CBC", cost: 600, result: "normal" },
        ],
        medications: [
          { name: "Cefazolin", dosage: "1g", days: 5 },
          { name: "Enoxaparin", dosage: "40mg", days: 14 },
          { name: "Tramadol", dosage: "50mg", days: 10 },
        ],
        readmitted: false,
      },
    ],
    reviews: [
      {
        doctorId: "DR006",
        rating: 5,
        comment: "Excellent surgical outcome",
        date: "2024-03-26",
      },
    ],
  },
  {
    patientId: "PT018",
    name: "Meena Krishnan",
    age: 63,
    gender: "Female",
    bloodGroup: "A-",
    city: "Bangalore",
    hospital: "Sunrise Health Institute",
    insuranceProvider: "HDFCErgo",
    insuranceCovered: true,
    admissions: [
      {
        admissionId: "ADM020",
        admittedAt: "2024-04-22",
        dischargedAt: "2024-04-28",
        department: "Oncology",
        doctorId: "DR002",
        diagnosis: "Breast Cancer - Stage 1",
        severity: "critical",
        totalBill: 210000,
        insurancePaid: 180000,
        patientPaid: 30000,
        tests: [
          { testName: "Mammogram", cost: 3500, result: "suspicious mass" },
          { testName: "Biopsy", cost: 12000, result: "malignant" },
          { testName: "Bone Scan", cost: 9000, result: "no metastasis" },
        ],
        medications: [
          { name: "Tamoxifen", dosage: "20mg", days: 365 },
          { name: "Anastrozole", dosage: "1mg", days: 180 },
        ],
        readmitted: false,
      },
    ],
    reviews: [
      {
        doctorId: "DR002",
        rating: 5,
        comment: "Dr handled everything with great care",
        date: "2024-04-29",
      },
    ],
  },
  {
    patientId: "PT019",
    name: "Sanjay Iyer",
    age: 47,
    gender: "Male",
    bloodGroup: "B+",
    city: "Bangalore",
    hospital: "Sunrise Health Institute",
    insuranceProvider: null,
    insuranceCovered: false,
    admissions: [
      {
        admissionId: "ADM021",
        admittedAt: "2024-05-10",
        dischargedAt: "2024-05-13",
        department: "Neurology",
        doctorId: "DR007",
        diagnosis: "Epilepsy",
        severity: "high",
        totalBill: 35000,
        insurancePaid: 0,
        patientPaid: 35000,
        tests: [
          { testName: "EEG", cost: 3500, result: "seizure activity" },
          { testName: "MRI Brain", cost: 8500, result: "normal" },
        ],
        medications: [
          { name: "Levetiracetam", dosage: "500mg", days: 90 },
          { name: "Valproate", dosage: "200mg", days: 90 },
        ],
        readmitted: false,
      },
    ],
    reviews: [],
  },
  {
    patientId: "PT020",
    name: "Divya Nair",
    age: 30,
    gender: "Female",
    bloodGroup: "O+",
    city: "Bangalore",
    hospital: "Sunrise Health Institute",
    insuranceProvider: "StarHealth",
    insuranceCovered: true,
    admissions: [
      {
        admissionId: "ADM022",
        admittedAt: "2024-06-15",
        dischargedAt: "2024-06-18",
        department: "Gastroenterology",
        doctorId: "DR010",
        diagnosis: "IBS",
        severity: "low",
        totalBill: 11000,
        insurancePaid: 9000,
        patientPaid: 2000,
        tests: [
          { testName: "Colonoscopy", cost: 6500, result: "mild inflammation" },
          { testName: "Stool Culture", cost: 900, result: "normal" },
        ],
        medications: [
          { name: "Mebeverine", dosage: "135mg", days: 30 },
          { name: "Probiotics", dosage: "daily", days: 60 },
        ],
        readmitted: false,
      },
    ],
    reviews: [
      {
        doctorId: "DR010",
        rating: 3,
        comment: "Average experience",
        date: "2024-06-19",
      },
    ],
  },
  {
    patientId: "PT021",
    name: "Kiran Rao",
    age: 50,
    gender: "Male",
    bloodGroup: "A+",
    city: "Bangalore",
    hospital: "Sunrise Health Institute",
    insuranceProvider: "ICICILombard",
    insuranceCovered: true,
    admissions: [
      {
        admissionId: "ADM023",
        admittedAt: "2024-07-12",
        dischargedAt: "2024-07-16",
        department: "Cardiology",
        doctorId: "DR001",
        diagnosis: "Angina",
        severity: "high",
        totalBill: 38000,
        insurancePaid: 32000,
        patientPaid: 6000,
        tests: [
          { testName: "Stress Test", cost: 4500, result: "positive" },
          { testName: "Angiogram", cost: 15000, result: "70% blockage" },
        ],
        medications: [
          { name: "Atorvastatin", dosage: "40mg", days: 90 },
          { name: "Aspirin", dosage: "75mg", days: 90 },
          { name: "Isosorbide", dosage: "20mg", days: 30 },
        ],
        readmitted: false,
      },
    ],
    reviews: [],
  },
  {
    patientId: "PT022",
    name: "Lalitha Bhat",
    age: 66,
    gender: "Female",
    bloodGroup: "B-",
    city: "Bangalore",
    hospital: "Sunrise Health Institute",
    insuranceProvider: "HDFCErgo",
    insuranceCovered: true,
    admissions: [
      {
        admissionId: "ADM024",
        admittedAt: "2024-08-20",
        dischargedAt: "2024-08-27",
        department: "Endocrinology",
        doctorId: "DR005",
        diagnosis: "Hypothyroidism",
        severity: "low",
        totalBill: 9500,
        insurancePaid: 8000,
        patientPaid: 1500,
        tests: [
          { testName: "TSH Test", cost: 800, result: "elevated" },
          { testName: "T3 T4", cost: 1200, result: "low T4" },
        ],
        medications: [{ name: "Levothyroxine", dosage: "50mcg", days: 90 }],
        readmitted: false,
      },
    ],
    reviews: [
      {
        doctorId: "DR005",
        rating: 4,
        comment: "Clear explanation",
        date: "2024-08-28",
      },
    ],
  },
  {
    patientId: "PT023",
    name: "Ajay Pillai",
    age: 34,
    gender: "Male",
    bloodGroup: "O-",
    city: "Bangalore",
    hospital: "Sunrise Health Institute",
    insuranceProvider: null,
    insuranceCovered: false,
    admissions: [
      {
        admissionId: "ADM025",
        admittedAt: "2024-09-05",
        dischargedAt: "2024-09-06",
        department: "Emergency",
        doctorId: "DR009",
        diagnosis: "Road Accident - Multiple Injuries",
        severity: "critical",
        totalBill: 72000,
        insurancePaid: 0,
        patientPaid: 72000,
        tests: [
          { testName: "CT Head", cost: 6500, result: "no intracranial bleed" },
          { testName: "X-Ray Chest", cost: 900, result: "rib fracture" },
          { testName: "Blood CBC", cost: 600, result: "low Hb" },
        ],
        medications: [
          { name: "Tramadol", dosage: "50mg", days: 7 },
          { name: "Iron Supplement", dosage: "150mg", days: 30 },
        ],
        readmitted: false,
      },
    ],
    reviews: [],
  },
  // ─── Additional patients for rich data ───────
  {
    patientId: "PT024",
    name: "Rekha Pillai",
    age: 53,
    gender: "Female",
    bloodGroup: "A+",
    city: "Mumbai",
    hospital: "City General Hospital",
    insuranceProvider: "StarHealth",
    insuranceCovered: true,
    admissions: [
      {
        admissionId: "ADM026",
        admittedAt: "2024-10-01",
        dischargedAt: "2024-10-05",
        department: "Cardiology",
        doctorId: "DR001",
        diagnosis: "Hypertension",
        severity: "moderate",
        totalBill: 25000,
        insurancePaid: 21000,
        patientPaid: 4000,
        tests: [
          { testName: "ECG", cost: 1500, result: "normal" },
          { testName: "Blood Pressure", cost: 300, result: "high" },
        ],
        medications: [{ name: "Amlodipine", dosage: "10mg", days: 30 }],
        readmitted: false,
      },
    ],
    reviews: [],
  },
  {
    patientId: "PT025",
    name: "Vinod Chandra",
    age: 72,
    gender: "Male",
    bloodGroup: "B+",
    city: "Delhi",
    hospital: "Apollo Medical Centre",
    insuranceProvider: "ICICILombard",
    insuranceCovered: true,
    admissions: [
      {
        admissionId: "ADM027",
        admittedAt: "2024-10-10",
        dischargedAt: "2024-10-18",
        department: "Orthopedics",
        doctorId: "DR006",
        diagnosis: "Spinal Stenosis",
        severity: "high",
        totalBill: 98000,
        insurancePaid: 85000,
        patientPaid: 13000,
        tests: [
          { testName: "MRI Spine", cost: 9000, result: "canal narrowing" },
          { testName: "X-Ray Spine", cost: 1200, result: "degeneration" },
        ],
        medications: [
          { name: "Gabapentin", dosage: "300mg", days: 30 },
          { name: "Tramadol", dosage: "50mg", days: 14 },
        ],
        readmitted: false,
      },
    ],
    reviews: [
      {
        doctorId: "DR006",
        rating: 3,
        comment: "Recovery was slow",
        date: "2024-10-19",
      },
    ],
  },
  // ─── Edge case patients ──────────────────────
  {
    patientId: "PT026",
    name: "Zara Khan",
    age: 22,
    gender: "Female",
    bloodGroup: "AB+",
    city: "Delhi",
    hospital: "Apollo Medical Centre",
    insuranceProvider: null,
    insuranceCovered: false,
    admissions: [], // Patient registered but NO admissions yet
    reviews: [],
  },
  {
    patientId: "PT027",
    name: "Gopal Das",
    age: 80,
    gender: "Male",
    bloodGroup: "O+",
    city: "Bangalore",
    hospital: "Sunrise Health Institute",
    insuranceProvider: "StarHealth",
    insuranceCovered: true,
    admissions: [
      {
        admissionId: "ADM028",
        admittedAt: "2024-11-01",
        dischargedAt: "2024-11-08",
        department: "Cardiology",
        doctorId: "DR001",
        diagnosis: "Heart Block",
        severity: "critical",
        totalBill: 95000,
        insurancePaid: 80000,
        patientPaid: 15000,
        tests: [
          { testName: "ECG", cost: 1500, result: "complete heart block" },
          { testName: "Echocardiogram", cost: 5500, result: "EF 40%" },
        ],
        medications: [
          { name: "Atropine", dosage: "0.5mg", days: 3 },
          { name: "Isoproterenol", dosage: "2mg", days: 5 },
        ],
        readmitted: false,
      },
      {
        admissionId: "ADM029",
        admittedAt: "2024-11-20",
        dischargedAt: "2024-11-22",
        department: "Cardiology",
        doctorId: "DR001",
        diagnosis: "Pacemaker Complication",
        severity: "high",
        totalBill: 35000,
        insurancePaid: 30000,
        patientPaid: 5000,
        tests: [
          { testName: "ECG", cost: 1500, result: "pacing threshold elevated" },
          { testName: "Chest X-Ray", cost: 900, result: "lead displacement" },
        ],
        medications: [{ name: "Amiodarone", dosage: "200mg", days: 30 }],
        readmitted: true,
      },
    ],
    reviews: [],
  },
  {
    patientId: "PT028",
    name: "Fatima Sheikh",
    age: 36,
    gender: "Female",
    bloodGroup: "B+",
    city: "Mumbai",
    hospital: "City General Hospital",
    insuranceProvider: "HDFCErgo",
    insuranceCovered: true,
    admissions: [
      {
        admissionId: "ADM030",
        admittedAt: "2024-11-15",
        dischargedAt: "2024-11-20",
        department: "Pulmonology",
        doctorId: "DR008",
        diagnosis: "Tuberculosis",
        severity: "high",
        totalBill: 42000,
        insurancePaid: 35000,
        patientPaid: 7000,
        tests: [
          { testName: "Sputum Culture", cost: 2200, result: "MTB positive" },
          { testName: "Chest X-Ray", cost: 900, result: "cavitation" },
          { testName: "CBNAAT", cost: 3500, result: "rifampicin sensitive" },
        ],
        medications: [
          { name: "Rifampicin", dosage: "600mg", days: 180 },
          { name: "Isoniazid", dosage: "300mg", days: 180 },
          { name: "Ethambutol", dosage: "800mg", days: 60 },
        ],
        readmitted: false,
      },
    ],
    reviews: [],
  },
  {
    patientId: "PT029",
    name: "Rohan Desai",
    age: 19,
    gender: "Male",
    bloodGroup: "A+",
    city: "Mumbai",
    hospital: "City General Hospital",
    insuranceProvider: null,
    insuranceCovered: false,
    admissions: [
      {
        admissionId: "ADM031",
        admittedAt: "2024-12-01",
        dischargedAt: "2024-12-02",
        department: "Emergency",
        doctorId: "DR009",
        diagnosis: "Dengue Fever",
        severity: "moderate",
        totalBill: 14000,
        insurancePaid: 0,
        patientPaid: 14000,
        tests: [
          { testName: "NS1 Antigen", cost: 1800, result: "positive" },
          { testName: "Platelet Count", cost: 600, result: "low" },
        ],
        medications: [
          { name: "Paracetamol", dosage: "500mg", days: 5 },
          { name: "ORS", dosage: "oral", days: 5 },
        ],
        readmitted: false,
      },
    ],
    reviews: [],
  },
  {
    patientId: "PT030",
    name: "Indira Prasad",
    age: 58,
    gender: "Female",
    bloodGroup: "O-",
    city: "Bangalore",
    hospital: "Sunrise Health Institute",
    insuranceProvider: "ICICILombard",
    insuranceCovered: true,
    admissions: [
      {
        admissionId: "ADM032",
        admittedAt: "2024-12-10",
        dischargedAt: "2024-12-14",
        department: "Nephrology",
        doctorId: "DR012",
        diagnosis: "Chronic Kidney Disease Stage 3",
        severity: "high",
        totalBill: 48000,
        insurancePaid: 40000,
        patientPaid: 8000,
        tests: [
          { testName: "Creatinine", cost: 500, result: "2.8 mg/dL" },
          { testName: "eGFR", cost: 700, result: "38 mL/min" },
          { testName: "Kidney Ultrasound", cost: 2500, result: "reduced size" },
        ],
        medications: [
          { name: "Amlodipine", dosage: "5mg", days: 90 },
          { name: "Erythropoietin", dosage: "4000IU", days: 14 },
          { name: "Sodium Bicarbonate", dosage: "500mg", days: 30 },
        ],
        readmitted: false,
      },
    ],
    reviews: [
      {
        doctorId: "DR012",
        rating: 4,
        comment: "Very detailed consultation",
        date: "2024-12-15",
      },
    ],
  },
];

// ─── DOCTORS REFERENCE TABLE ────────────────────────────────
export const doctors = [
  {
    doctorId: "DR001",
    name: "Dr. Suresh Malhotra",
    department: "Cardiology",
    hospital: "All",
    experience: 18,
    consultationFee: 800,
  },
  {
    doctorId: "DR002",
    name: "Dr. Amrita Bose",
    department: "Oncology",
    hospital: "Apollo Medical Centre",
    experience: 14,
    consultationFee: 1200,
  },
  {
    doctorId: "DR003",
    name: "Dr. Nikhil Verma",
    department: "Ophthalmology",
    hospital: "Apollo Medical Centre",
    experience: 10,
    consultationFee: 600,
  },
  {
    doctorId: "DR004",
    name: "Dr. Sunanda Pillai",
    department: "Gynecology",
    hospital: "All",
    experience: 12,
    consultationFee: 700,
  },
  {
    doctorId: "DR005",
    name: "Dr. Rajan Khanna",
    department: "Endocrinology",
    hospital: "Apollo Medical Centre",
    experience: 16,
    consultationFee: 900,
  },
  {
    doctorId: "DR006",
    name: "Dr. Pradeep Sharma",
    department: "Orthopedics",
    hospital: "All",
    experience: 20,
    consultationFee: 1000,
  },
  {
    doctorId: "DR007",
    name: "Dr. Laleh Irani",
    department: "Neurology",
    hospital: "All",
    experience: 15,
    consultationFee: 1100,
  },
  {
    doctorId: "DR008",
    name: "Dr. Mohan Rao",
    department: "Pulmonology",
    hospital: "Apollo Medical Centre",
    experience: 11,
    consultationFee: 750,
  },
  {
    doctorId: "DR009",
    name: "Dr. Tanya Kapoor",
    department: "Emergency",
    hospital: "All",
    experience: 8,
    consultationFee: 500,
  },
  {
    doctorId: "DR010",
    name: "Dr. Vikas Menon",
    department: "Gastroenterology",
    hospital: "All",
    experience: 13,
    consultationFee: 850,
  },
  {
    doctorId: "DR011",
    name: "Dr. Sonali Desai",
    department: "Dermatology",
    hospital: "City General Hospital",
    experience: 9,
    consultationFee: 600,
  },
  {
    doctorId: "DR012",
    name: "Dr. Arvind Nair",
    department: "Urology/Nephrology",
    hospital: "All",
    experience: 17,
    consultationFee: 950,
  },
];
