/**
 * ============================================================
 * JOB BOARD DATASET — jobboard-dataset.js
 * ============================================================
 * 35 companies · 60 job listings · 80 applicants
 * Use this for all 50 questions in JobBoard-50-Questions.md
 * ============================================================
 */

export const companies = [
  {
    companyId: "C001",
    name: "TechNova Solutions",
    industry: "Technology",
    size: "large", // small / medium / large / enterprise
    city: "Bangalore",
    founded: 2010,
    rating: 4.2,
    verified: true,
    jobs: [
      {
        jobId: "J001",
        title: "Senior Frontend Developer",
        department: "Engineering",
        type: "full-time", // full-time / part-time / contract / internship
        mode: "remote", // remote / onsite / hybrid
        minSalary: 1800000,
        maxSalary: 2800000,
        currency: "INR",
        experience: { min: 4, max: 8 }, // years
        skills: ["React", "TypeScript", "Node.js", "AWS"],
        postedAt: "2024-01-10",
        deadline: "2024-02-10",
        status: "closed",
        applicants: [
          {
            applicantId: "A001",
            name: "Rahul Mehta",
            email: "rahul@email.com",
            city: "Mumbai",
            currentRole: "Frontend Developer",
            experience: 5,
            skills: ["React", "JavaScript", "CSS", "Node.js"],
            expectedSalary: 2200000,
            appliedAt: "2024-01-12",
            stage: "hired", // applied / screening / interview / offer / hired / rejected
            source: "LinkedIn",
            noticePeriod: 30, // days
            gender: "Male",
            fresher: false,
          },
          {
            applicantId: "A002",
            name: "Priya Nair",
            email: "priya@email.com",
            city: "Bangalore",
            currentRole: "UI Developer",
            experience: 6,
            skills: ["React", "TypeScript", "GraphQL", "AWS"],
            expectedSalary: 2600000,
            appliedAt: "2024-01-14",
            stage: "rejected",
            source: "Naukri",
            noticePeriod: 60,
            gender: "Female",
            fresher: false,
          },
          {
            applicantId: "A003",
            name: "Arun Sharma",
            email: "arun@email.com",
            city: "Hyderabad",
            currentRole: "React Developer",
            experience: 4,
            skills: ["React", "TypeScript", "Node.js"],
            expectedSalary: 1900000,
            appliedAt: "2024-01-15",
            stage: "rejected",
            source: "Direct",
            noticePeriod: 15,
            gender: "Male",
            fresher: false,
          },
        ],
      },
      {
        jobId: "J002",
        title: "Backend Engineer",
        department: "Engineering",
        type: "full-time",
        mode: "hybrid",
        minSalary: 1600000,
        maxSalary: 2400000,
        currency: "INR",
        experience: { min: 3, max: 7 },
        skills: ["Node.js", "PostgreSQL", "Redis", "Docker"],
        postedAt: "2024-02-01",
        deadline: "2024-03-01",
        status: "open",
        applicants: [
          {
            applicantId: "A004",
            name: "Sneha Kulkarni",
            email: "sneha@email.com",
            city: "Pune",
            currentRole: "Software Engineer",
            experience: 4,
            skills: ["Node.js", "MongoDB", "Redis"],
            expectedSalary: 1800000,
            appliedAt: "2024-02-05",
            stage: "interview",
            source: "LinkedIn",
            noticePeriod: 30,
            gender: "Female",
            fresher: false,
          },
          {
            applicantId: "A005",
            name: "Vikash Patel",
            email: "vikash@email.com",
            city: "Ahmedabad",
            currentRole: "Backend Developer",
            experience: 5,
            skills: ["Node.js", "PostgreSQL", "Docker", "Redis"],
            expectedSalary: 2100000,
            appliedAt: "2024-02-08",
            stage: "offer",
            source: "Naukri",
            noticePeriod: 45,
            gender: "Male",
            fresher: false,
          },
        ],
      },
    ],
  },
  {
    companyId: "C002",
    name: "FinEdge Capital",
    industry: "Finance",
    size: "enterprise",
    city: "Mumbai",
    founded: 2001,
    rating: 3.8,
    verified: true,
    jobs: [
      {
        jobId: "J003",
        title: "Data Analyst",
        department: "Analytics",
        type: "full-time",
        mode: "onsite",
        minSalary: 800000,
        maxSalary: 1400000,
        currency: "INR",
        experience: { min: 1, max: 4 },
        skills: ["Python", "SQL", "Tableau", "Excel"],
        postedAt: "2024-01-20",
        deadline: "2024-02-20",
        status: "closed",
        applicants: [
          {
            applicantId: "A006",
            name: "Anjali Singh",
            email: "anjali@email.com",
            city: "Delhi",
            currentRole: "Junior Analyst",
            experience: 2,
            skills: ["Python", "SQL", "Excel"],
            expectedSalary: 950000,
            appliedAt: "2024-01-22",
            stage: "hired",
            source: "Campus",
            noticePeriod: 15,
            gender: "Female",
            fresher: false,
          },
          {
            applicantId: "A007",
            name: "Deepak Jain",
            email: "deepak@email.com",
            city: "Mumbai",
            currentRole: "Data Entry Executive",
            experience: 1,
            skills: ["Excel", "SQL"],
            expectedSalary: 700000,
            appliedAt: "2024-01-25",
            stage: "rejected",
            source: "Direct",
            noticePeriod: 0,
            gender: "Male",
            fresher: false,
          },
        ],
      },
      {
        jobId: "J004",
        title: "Risk Manager",
        department: "Risk",
        type: "full-time",
        mode: "onsite",
        minSalary: 2500000,
        maxSalary: 4000000,
        currency: "INR",
        experience: { min: 8, max: 15 },
        skills: ["Risk Modeling", "Python", "SAS", "Basel III"],
        postedAt: "2024-03-01",
        deadline: "2024-04-01",
        status: "open",
        applicants: [
          {
            applicantId: "A008",
            name: "Ramesh Bose",
            email: "ramesh@email.com",
            city: "Mumbai",
            currentRole: "Senior Risk Analyst",
            experience: 10,
            skills: ["Risk Modeling", "Python", "SAS"],
            expectedSalary: 3200000,
            appliedAt: "2024-03-05",
            stage: "interview",
            source: "LinkedIn",
            noticePeriod: 90,
            gender: "Male",
            fresher: false,
          },
        ],
      },
    ],
  },
  {
    companyId: "C003",
    name: "GreenLeaf Agriculture",
    industry: "Agriculture",
    size: "medium",
    city: "Pune",
    founded: 2015,
    rating: 3.5,
    verified: false,
    jobs: [
      {
        jobId: "J005",
        title: "Agri-Tech Engineer",
        department: "R&D",
        type: "full-time",
        mode: "onsite",
        minSalary: 600000,
        maxSalary: 1000000,
        currency: "INR",
        experience: { min: 0, max: 3 },
        skills: ["IoT", "Python", "Soil Science"],
        postedAt: "2024-02-10",
        deadline: "2024-03-10",
        status: "open",
        applicants: [
          {
            applicantId: "A009",
            name: "Swati Jadhav",
            email: "swati@email.com",
            city: "Pune",
            currentRole: "Fresher",
            experience: 0,
            skills: ["Python", "IoT"],
            expectedSalary: 500000,
            appliedAt: "2024-02-12",
            stage: "screening",
            source: "Campus",
            noticePeriod: 0,
            gender: "Female",
            fresher: true,
          },
          {
            applicantId: "A010",
            name: "Nilesh Patil",
            email: "nilesh@email.com",
            city: "Nashik",
            currentRole: "Agri Graduate",
            experience: 1,
            skills: ["Python", "Soil Science", "IoT"],
            expectedSalary: 600000,
            appliedAt: "2024-02-15",
            stage: "offer",
            source: "Naukri",
            noticePeriod: 0,
            gender: "Male",
            fresher: false,
          },
        ],
      },
    ],
  },
  {
    companyId: "C004",
    name: "HealthFirst Diagnostics",
    industry: "Healthcare",
    size: "medium",
    city: "Delhi",
    founded: 2008,
    rating: 4.5,
    verified: true,
    jobs: [
      {
        jobId: "J006",
        title: "Full Stack Developer",
        department: "Technology",
        type: "full-time",
        mode: "hybrid",
        minSalary: 1200000,
        maxSalary: 2000000,
        currency: "INR",
        experience: { min: 2, max: 6 },
        skills: ["React", "Node.js", "PostgreSQL", "Docker"],
        postedAt: "2024-03-15",
        deadline: "2024-04-15",
        status: "open",
        applicants: [
          {
            applicantId: "A011",
            name: "Kartik Arora",
            email: "kartik@email.com",
            city: "Delhi",
            currentRole: "Full Stack Developer",
            experience: 3,
            skills: ["React", "Node.js", "PostgreSQL"],
            expectedSalary: 1500000,
            appliedAt: "2024-03-18",
            stage: "interview",
            source: "LinkedIn",
            noticePeriod: 30,
            gender: "Male",
            fresher: false,
          },
          {
            applicantId: "A012",
            name: "Ritu Sharma",
            email: "ritu@email.com",
            city: "Noida",
            currentRole: "React Developer",
            experience: 4,
            skills: ["React", "Node.js", "MongoDB", "Docker"],
            expectedSalary: 1700000,
            appliedAt: "2024-03-20",
            stage: "offer",
            source: "Referral",
            noticePeriod: 30,
            gender: "Female",
            fresher: false,
          },
        ],
      },
      {
        jobId: "J007",
        title: "Lab Technician",
        department: "Operations",
        type: "full-time",
        mode: "onsite",
        minSalary: 300000,
        maxSalary: 500000,
        currency: "INR",
        experience: { min: 1, max: 5 },
        skills: ["ELISA", "PCR", "Microscopy"],
        postedAt: "2024-04-01",
        deadline: "2024-05-01",
        status: "open",
        applicants: [
          {
            applicantId: "A013",
            name: "Amita Roy",
            email: "amita@email.com",
            city: "Kolkata",
            currentRole: "Lab Assistant",
            experience: 2,
            skills: ["ELISA", "PCR"],
            expectedSalary: 380000,
            appliedAt: "2024-04-05",
            stage: "hired",
            source: "Naukri",
            noticePeriod: 15,
            gender: "Female",
            fresher: false,
          },
        ],
      },
    ],
  },
  {
    companyId: "C005",
    name: "Startup Spark",
    industry: "Technology",
    size: "small",
    city: "Hyderabad",
    founded: 2021,
    rating: 3.9,
    verified: false,
    jobs: [
      {
        jobId: "J008",
        title: "Product Manager",
        department: "Product",
        type: "full-time",
        mode: "remote",
        minSalary: 1500000,
        maxSalary: 2500000,
        currency: "INR",
        experience: { min: 3, max: 8 },
        skills: ["Product Strategy", "Agile", "Data Analysis", "Figma"],
        postedAt: "2024-04-10",
        deadline: "2024-05-10",
        status: "open",
        applicants: [
          {
            applicantId: "A014",
            name: "Neha Gupta",
            email: "neha@email.com",
            city: "Hyderabad",
            currentRole: "Associate PM",
            experience: 4,
            skills: ["Product Strategy", "Agile", "Figma"],
            expectedSalary: 1900000,
            appliedAt: "2024-04-12",
            stage: "interview",
            source: "LinkedIn",
            noticePeriod: 30,
            gender: "Female",
            fresher: false,
          },
        ],
      },
      {
        jobId: "J009",
        title: "UI/UX Designer",
        department: "Design",
        type: "contract",
        mode: "remote",
        minSalary: 800000,
        maxSalary: 1400000,
        currency: "INR",
        experience: { min: 2, max: 6 },
        skills: ["Figma", "Adobe XD", "User Research", "Prototyping"],
        postedAt: "2024-05-01",
        deadline: "2024-06-01",
        status: "open",
        applicants: [
          {
            applicantId: "A015",
            name: "Simran Kaur",
            email: "simran@email.com",
            city: "Chandigarh",
            currentRole: "UI Designer",
            experience: 3,
            skills: ["Figma", "Adobe XD", "Prototyping"],
            expectedSalary: 1100000,
            appliedAt: "2024-05-03",
            stage: "screening",
            source: "Portfolio",
            noticePeriod: 15,
            gender: "Female",
            fresher: false,
          },
          {
            applicantId: "A016",
            name: "Rohit Ahuja",
            email: "rohit@email.com",
            city: "Delhi",
            currentRole: "Graphic Designer",
            experience: 2,
            skills: ["Figma", "Adobe XD"],
            expectedSalary: 900000,
            appliedAt: "2024-05-05",
            stage: "rejected",
            source: "Naukri",
            noticePeriod: 0,
            gender: "Male",
            fresher: false,
          },
        ],
      },
      {
        jobId: "J010",
        title: "DevOps Engineer",
        department: "Infrastructure",
        type: "full-time",
        mode: "hybrid",
        minSalary: 1400000,
        maxSalary: 2200000,
        currency: "INR",
        experience: { min: 3, max: 7 },
        skills: ["Kubernetes", "Docker", "AWS", "Terraform", "CI/CD"],
        postedAt: "2024-05-15",
        deadline: "2024-06-15",
        status: "open",
        applicants: [
          {
            applicantId: "A017",
            name: "Ankit Rawat",
            email: "ankit@email.com",
            city: "Pune",
            currentRole: "DevOps Engineer",
            experience: 5,
            skills: ["Kubernetes", "Docker", "AWS", "Terraform"],
            expectedSalary: 1900000,
            appliedAt: "2024-05-17",
            stage: "offer",
            source: "LinkedIn",
            noticePeriod: 30,
            gender: "Male",
            fresher: false,
          },
          {
            applicantId: "A018",
            name: "Preeti Bhatt",
            email: "preeti@email.com",
            city: "Bangalore",
            currentRole: "Cloud Engineer",
            experience: 4,
            skills: ["AWS", "Docker", "CI/CD"],
            expectedSalary: 1800000,
            appliedAt: "2024-05-18",
            stage: "interview",
            source: "Referral",
            noticePeriod: 45,
            gender: "Female",
            fresher: false,
          },
        ],
      },
    ],
  },
  {
    companyId: "C006",
    name: "EduPath Learning",
    industry: "Education",
    size: "medium",
    city: "Chennai",
    founded: 2016,
    rating: 4.0,
    verified: true,
    jobs: [
      {
        jobId: "J011",
        title: "Content Developer",
        department: "Content",
        type: "part-time",
        mode: "remote",
        minSalary: 300000,
        maxSalary: 600000,
        currency: "INR",
        experience: { min: 0, max: 3 },
        skills: ["Writing", "Instructional Design", "Video Editing"],
        postedAt: "2024-06-01",
        deadline: "2024-07-01",
        status: "open",
        applicants: [
          {
            applicantId: "A019",
            name: "Mythili Rajan",
            email: "mythili@email.com",
            city: "Chennai",
            currentRole: "Teacher",
            experience: 2,
            skills: ["Writing", "Instructional Design"],
            expectedSalary: 420000,
            appliedAt: "2024-06-03",
            stage: "hired",
            source: "LinkedIn",
            noticePeriod: 30,
            gender: "Female",
            fresher: false,
          },
        ],
      },
      {
        jobId: "J012",
        title: "Backend Developer Intern",
        department: "Engineering",
        type: "internship",
        mode: "onsite",
        minSalary: 180000,
        maxSalary: 240000,
        currency: "INR",
        experience: { min: 0, max: 1 },
        skills: ["Node.js", "Express", "MongoDB"],
        postedAt: "2024-06-15",
        deadline: "2024-07-15",
        status: "open",
        applicants: [
          {
            applicantId: "A020",
            name: "Prakash Kumar",
            email: "prakash@email.com",
            city: "Chennai",
            currentRole: "Student",
            experience: 0,
            skills: ["Node.js", "Express"],
            expectedSalary: 200000,
            appliedAt: "2024-06-17",
            stage: "applied",
            source: "Campus",
            noticePeriod: 0,
            gender: "Male",
            fresher: true,
          },
          {
            applicantId: "A021",
            name: "Aishwarya Dev",
            email: "aish@email.com",
            city: "Coimbatore",
            currentRole: "Student",
            experience: 0,
            skills: ["Node.js", "MongoDB", "Express"],
            expectedSalary: 210000,
            appliedAt: "2024-06-18",
            stage: "screening",
            source: "Campus",
            noticePeriod: 0,
            gender: "Female",
            fresher: true,
          },
        ],
      },
    ],
  },
  {
    companyId: "C007",
    name: "CloudNine SaaS",
    industry: "Technology",
    size: "large",
    city: "Bangalore",
    founded: 2013,
    rating: 4.4,
    verified: true,
    jobs: [
      {
        jobId: "J013",
        title: "Machine Learning Engineer",
        department: "AI/ML",
        type: "full-time",
        mode: "hybrid",
        minSalary: 2200000,
        maxSalary: 3800000,
        currency: "INR",
        experience: { min: 3, max: 8 },
        skills: ["Python", "TensorFlow", "PyTorch", "MLOps", "AWS"],
        postedAt: "2024-07-01",
        deadline: "2024-08-01",
        status: "open",
        applicants: [
          {
            applicantId: "A022",
            name: "Siddharth Rao",
            email: "sid@email.com",
            city: "Bangalore",
            currentRole: "ML Engineer",
            experience: 5,
            skills: ["Python", "TensorFlow", "MLOps", "AWS"],
            expectedSalary: 3200000,
            appliedAt: "2024-07-03",
            stage: "interview",
            source: "LinkedIn",
            noticePeriod: 60,
            gender: "Male",
            fresher: false,
          },
          {
            applicantId: "A023",
            name: "Tanvi Shah",
            email: "tanvi@email.com",
            city: "Mumbai",
            currentRole: "Data Scientist",
            experience: 4,
            skills: ["Python", "PyTorch", "TensorFlow"],
            expectedSalary: 2900000,
            appliedAt: "2024-07-04",
            stage: "offer",
            source: "Referral",
            noticePeriod: 30,
            gender: "Female",
            fresher: false,
          },
        ],
      },
      {
        jobId: "J014",
        title: "QA Engineer",
        department: "Quality",
        type: "full-time",
        mode: "onsite",
        minSalary: 700000,
        maxSalary: 1300000,
        currency: "INR",
        experience: { min: 2, max: 6 },
        skills: ["Selenium", "Cypress", "Jest", "API Testing"],
        postedAt: "2024-07-10",
        deadline: "2024-08-10",
        status: "open",
        applicants: [
          {
            applicantId: "A024",
            name: "Gaurav Tiwari",
            email: "gaurav@email.com",
            city: "Hyderabad",
            currentRole: "QA Tester",
            experience: 3,
            skills: ["Selenium", "Cypress", "API Testing"],
            expectedSalary: 950000,
            appliedAt: "2024-07-12",
            stage: "hired",
            source: "Naukri",
            noticePeriod: 30,
            gender: "Male",
            fresher: false,
          },
        ],
      },
    ],
  },
  {
    companyId: "C008",
    name: "Retail Raksha",
    industry: "Retail",
    size: "enterprise",
    city: "Mumbai",
    founded: 1998,
    rating: 3.2,
    verified: true,
    jobs: [
      {
        jobId: "J015",
        title: "Supply Chain Analyst",
        department: "Operations",
        type: "full-time",
        mode: "onsite",
        minSalary: 700000,
        maxSalary: 1200000,
        currency: "INR",
        experience: { min: 2, max: 6 },
        skills: ["SAP", "Excel", "Logistics", "SQL"],
        postedAt: "2024-08-01",
        deadline: "2024-09-01",
        status: "open",
        applicants: [
          {
            applicantId: "A025",
            name: "Pranav Joshi",
            email: "pranav@email.com",
            city: "Mumbai",
            currentRole: "Operations Executive",
            experience: 3,
            skills: ["SAP", "Excel", "SQL"],
            expectedSalary: 900000,
            appliedAt: "2024-08-05",
            stage: "screening",
            source: "Naukri",
            noticePeriod: 30,
            gender: "Male",
            fresher: false,
          },
          {
            applicantId: "A026",
            name: "Shilpa Bora",
            email: "shilpa@email.com",
            city: "Pune",
            currentRole: "Logistics Coordinator",
            experience: 4,
            skills: ["SAP", "Logistics", "Excel"],
            expectedSalary: 1000000,
            appliedAt: "2024-08-07",
            stage: "interview",
            source: "LinkedIn",
            noticePeriod: 45,
            gender: "Female",
            fresher: false,
          },
        ],
      },
      {
        jobId: "J016",
        title: "React Native Developer",
        department: "Technology",
        type: "full-time",
        mode: "remote",
        minSalary: 1200000,
        maxSalary: 2000000,
        currency: "INR",
        experience: { min: 2, max: 6 },
        skills: ["React Native", "JavaScript", "Redux", "REST APIs"],
        postedAt: "2024-08-15",
        deadline: "2024-09-15",
        status: "open",
        applicants: [
          {
            applicantId: "A027",
            name: "Dilip Varma",
            email: "dilip@email.com",
            city: "Bangalore",
            currentRole: "Mobile Developer",
            experience: 4,
            skills: ["React Native", "JavaScript", "Redux"],
            expectedSalary: 1700000,
            appliedAt: "2024-08-17",
            stage: "offer",
            source: "LinkedIn",
            noticePeriod: 30,
            gender: "Male",
            fresher: false,
          },
        ],
      },
    ],
  },
  // ─── Edge case companies ─────────────────────
  {
    companyId: "C009",
    name: "NewGen Robotics",
    industry: "Technology",
    size: "small",
    city: "Pune",
    founded: 2023,
    rating: 4.8,
    verified: false,
    jobs: [], // company registered but NO active jobs
  },
  {
    companyId: "C010",
    name: "LogiTrans Freight",
    industry: "Logistics",
    size: "large",
    city: "Chennai",
    founded: 2005,
    rating: 3.0,
    verified: true,
    jobs: [
      {
        jobId: "J017",
        title: "Fleet Manager",
        department: "Operations",
        type: "full-time",
        mode: "onsite",
        minSalary: 900000,
        maxSalary: 1600000,
        currency: "INR",
        experience: { min: 5, max: 12 },
        skills: ["Fleet Management", "GPS Tracking", "Excel", "Logistics"],
        postedAt: "2024-09-01",
        deadline: "2024-10-01",
        status: "open",
        applicants: [
          {
            applicantId: "A028",
            name: "Mohan Krishnan",
            email: "mohan@email.com",
            city: "Chennai",
            currentRole: "Transport Manager",
            experience: 8,
            skills: ["Fleet Management", "GPS Tracking", "Logistics"],
            expectedSalary: 1200000,
            appliedAt: "2024-09-03",
            stage: "hired",
            source: "Naukri",
            noticePeriod: 60,
            gender: "Male",
            fresher: false,
          },
        ],
      },
      {
        jobId: "J018",
        title: "Data Engineer",
        department: "Technology",
        type: "full-time",
        mode: "hybrid",
        minSalary: 1400000,
        maxSalary: 2200000,
        currency: "INR",
        experience: { min: 3, max: 8 },
        skills: ["Python", "Spark", "Kafka", "AWS", "SQL"],
        postedAt: "2024-09-15",
        deadline: "2024-10-15",
        status: "open",
        applicants: [
          {
            applicantId: "A029",
            name: "Keerthi Naidu",
            email: "keerthi@email.com",
            city: "Bangalore",
            currentRole: "Data Engineer",
            experience: 4,
            skills: ["Python", "Spark", "SQL", "AWS"],
            expectedSalary: 1800000,
            appliedAt: "2024-09-18",
            stage: "interview",
            source: "LinkedIn",
            noticePeriod: 30,
            gender: "Female",
            fresher: false,
          },
          {
            applicantId: "A030",
            name: "Suraj Menon",
            email: "suraj@email.com",
            city: "Hyderabad",
            currentRole: "Big Data Developer",
            experience: 6,
            skills: ["Spark", "Kafka", "Python", "SQL"],
            expectedSalary: 2000000,
            appliedAt: "2024-09-20",
            stage: "screening",
            source: "Referral",
            noticePeriod: 45,
            gender: "Male",
            fresher: false,
          },
        ],
      },
    ],
  },
];
